PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS licenses(id TEXT PRIMARY KEY, hash TEXT NOT NULL UNIQUE, label TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, expires INTEGER, max_devices INTEGER NOT NULL, max_sessions INTEGER NOT NULL, ip_mode TEXT NOT NULL, allowed_ip TEXT, device_mode TEXT NOT NULL, allowed_device TEXT, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS devices(id TEXT PRIMARY KEY, key_id TEXT NOT NULL REFERENCES licenses(id), proof TEXT NOT NULL, label TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, created INTEGER NOT NULL, UNIQUE(key_id,proof));
CREATE TABLE IF NOT EXISTS sessions(id TEXT PRIMARY KEY, hash TEXT NOT NULL UNIQUE, key_id TEXT NOT NULL REFERENCES licenses(id), device_id TEXT NOT NULL REFERENCES devices(id), ip TEXT NOT NULL, ua TEXT NOT NULL, created INTEGER NOT NULL, seen INTEGER NOT NULL, expires INTEGER NOT NULL, revoked INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS sessions_key ON sessions(key_id,revoked,expires);
CREATE TABLE IF NOT EXISTS ip_history(session_id TEXT NOT NULL REFERENCES sessions(id), ip TEXT NOT NULL, first_seen INTEGER NOT NULL, last_seen INTEGER NOT NULL, PRIMARY KEY(session_id,ip));
CREATE TABLE IF NOT EXISTS attempts(ip_hash TEXT NOT NULL, minute INTEGER NOT NULL, count INTEGER NOT NULL, PRIMARY KEY(ip_hash,minute));
CREATE TABLE IF NOT EXISTS audit(id TEXT PRIMARY KEY, actor TEXT NOT NULL, action TEXT NOT NULL, target TEXT, created INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS omr_jobs(id TEXT PRIMARY KEY, key_id TEXT NOT NULL REFERENCES licenses(id), created INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS admin_sessions(hash TEXT PRIMARY KEY, actor TEXT NOT NULL, credential TEXT NOT NULL, created INTEGER NOT NULL, expires INTEGER NOT NULL, revoked INTEGER NOT NULL DEFAULT 0);
