import test from 'node:test';import assert from 'node:assert/strict';
import {KEYS,label} from '../sito/public/app/engine.mjs';import {harmonizeTonal,tonalIssues}from'../sito/public/app/tonal.mjs';import{proposeHarmonyEdit,CADENCES}from'../sito/public/app/actions.mjs';
const base={bass:[48,53,55,48],key:'Do maggiore',level:3,seventhsEnabled:false,meter:'4/4',durations:[16,16,16,16]};
function check(sol,args){sol.forEach((c,i)=>assert.deepEqual(tonalIssues(i?sol[i-1]:null,c,args.key,3,{preparationUnits:16,minimumPreparationUnits:16}),[],`nota ${i+1}`))}
test('aggiungere V7 risolve la settima e non modifica gli input',()=>{const solution=harmonizeTonal(base).solutions[0],before=JSON.stringify({base,solution}),r=proposeHarmonyEdit({args:base,solution,index:2,kind:'seventh'});assert.ok(r.proposals.length,r.message);const p=r.proposals[0];assert.equal(label(p.solution[2]),'V7');check(p.solution,base);assert.equal(JSON.stringify({base,solution}),before);assert.deepEqual(p.bass,base.bass);assert.equal(p.changes.length,1)});
test('tutte le cadenze proposte hanno davvero i gradi richiesti e parti valide',()=>{const solution=harmonizeTonal(base).solutions[0],r=proposeHarmonyEdit({args:base,solution,index:3,kind:'cadence'});assert.equal(r.proposals.length,6);for(const p of r.proposals){const spec=CADENCES[p.type],tail=p.solution.slice(-spec.roots.length);assert.deepEqual(tail.map(c=>c.root),spec.roots);assert.ok(tail.every(c=>!c.seventh&&c.inv===0));if(spec.sopranoTonic)assert.equal(tail.at(-1).voices[3]%12,0);check(p.solution,base)}});
test('cadenze e settime sono trasponibili anche in minore',()=>{for(const [key,bass]of[['Re maggiore',[50,55,57,50]],['Fa maggiore',[53,58,60,53]],['Sol minore',[43,48,50,43]]]){const args={...base,key,bass},solution=harmonizeTonal(args).solutions[0];assert.ok(solution);for(const kind of ['cadence','seventh']){const r=proposeHarmonyEdit({args,solution,index:kind==='cadence'?3:2,kind,cadenceType:'perfect'});assert.ok(r.proposals.length,r.message);r.proposals.forEach(p=>check(p.solution,args))}}});
test('le note bloccate non sono sbloccate per forzare una settima',()=>{const solution=harmonizeTonal(base).solutions[0],locks=Object.fromEntries(solution.map((c,i)=>[i,Object.fromEntries(c.voices.map((n,v)=>[v,n]))]));const r=proposeHarmonyEdit({args:{...base,locks},solution,index:2,kind:'seventh'});assert.equal(r.proposals.length,0);assert.match(r.message,/note bloccate/)});
test('ultima nota, grado escluso e arrivo troppo precoce hanno esito esplicito',()=>{const solution=harmonizeTonal(base).solutions[0];assert.match(proposeHarmonyEdit({args:base,solution,index:3,kind:'seventh'}).message,/successiva/);assert.equal(proposeHarmonyEdit({args:base,solution,index:0,kind:'cadence'}).proposals.length,0);const b={...solution[2],root:6};assert.match(proposeHarmonyEdit({args:base,solution:solution.map((c,i)=>i===2?b:c),index:2,kind:'seventh'}).message,/profilo teorico/)});
test('la richiesta confermata mantiene V7 durante il ricalcolo',()=>{const solution=harmonizeTonal(base).solutions[0],p=proposeHarmonyEdit({args:base,solution,index:2,kind:'seventh'}).proposals[0];const r=harmonizeTonal({...base,bass:p.bass,harmonicRequests:p.requests,seventhsEnabled:p.seventhsEnabled,allowedSevenths:p.allowedSevenths});assert.ok(r.solutions.length);assert.ok(r.solutions.every(s=>s[2].seventh));assert.equal(harmonizeTonal({...base,harmonicRequests:p.requests}).solutions.length,0)});
test('se necessario cambia il basso in V42 e risolve su I6; legature e blocchi restano rispettati',()=>{const args={...base,bass:[48,53,55,52]},solution=harmonizeTonal(args).solutions[0];args.locks={2:Object.fromEntries(solution[2].voices.slice(1).map((n,j)=>[j+1,n]))};const p=proposeHarmonyEdit({args,solution,index:2,kind:'seventh'}).proposals[0];assert.ok(p);assert.equal(p.bass[2],53);assert.equal(label(p.solution[2]),'V42');assert.equal(label(p.solution[3]),'I6');assert.deepEqual(p.solution[2].voices.slice(1),solution[2].voices.slice(1));check(p.solution,args);assert.equal(proposeHarmonyEdit({args,solution,index:2,kind:'seventh',tiedIndexes:[2]}).proposals.length,0)});
test('II selezionato diventa II7 anche partendo dal livello 1, con preparazione e risoluzione',()=>{const args={...base,bass:[48,50,55,48],level:1},solution=harmonizeTonal(args).solutions[0];assert.equal(label(solution[1]),'II');const r=proposeHarmonyEdit({args,solution,index:1,kind:'seventh'});assert.ok(r.proposals.length,r.message);assert.equal(label(r.proposals[0].solution[1]),'II7');assert.equal(r.proposals[0].solution[2].root,4);check(r.proposals[0].solution,args)});
