import test from 'node:test';import assert from 'node:assert/strict';
import {KEYS,label} from '../sito/public/app/engine.mjs';import {harmonizeTonal,tonalIssues} from '../sito/public/app/tonal.mjs';import {proposeAutomaticSevenths} from '../sito/public/app/automatic-sevenths.mjs';
const base={bass:[53,50,55,48],key:'Do maggiore',level:1,meter:'4/4',durations:[16,16,16,16]};
function verify(p,args){assert.deepEqual(p.bass,args.bass);p.solution.forEach((c,i)=>assert.deepEqual(tonalIssues(p.solution[i-1],c,args.key,3,{preparationUnits:args.durations[i-1],minimumPreparationUnits:16}),[]));}
test('IV II V I diventa IV II7 V7 I; gradi e basso immutati, ricalcolo stabile',()=>{const solution=harmonizeTonal(base).solutions[0],before=JSON.stringify({base,solution}),p=proposeAutomaticSevenths({args:base,solution,degrees:[1,4]}).proposals[0];assert.ok(p);assert.deepEqual(p.solution.map(label),['IV','II7','V7','I']);verify(p,base);assert.equal(JSON.stringify({base,solution}),before);const r=harmonizeTonal({...base,level:3,harmonicRequests:p.requests,seventhsEnabled:true,allowedSevenths:p.allowedSevenths});assert.ok(r.solutions.length);r.solutions.forEach(s=>assert.deepEqual(s.map(label),['IV','II7','V7','I']));});
test('scelta solo II o solo V e nessuna settima sull’ultimo accordo',()=>{const solution=harmonizeTonal(base).solutions[0];for(const degrees of [[1],[4]]){const p=proposeAutomaticSevenths({args:base,solution,degrees}).proposals[0];assert.ok(p);assert.ok(p.solution.every(c=>!c.seventh||degrees.includes(c.root)));assert.equal(p.solution.at(-1).seventh,false);verify(p,base)}assert.match(proposeAutomaticSevenths({args:base,solution,degrees:[]}).message,/Scegli/);});
test('tutte le tonalità: solo settime preparate e risolte; nessuna modifica al basso',()=>{let count=0;for(const [key,k] of Object.entries(KEYS)){const tonic=48+k.tonic%12,args={...base,key,bass:[tonic+k.steps[3],tonic+k.steps[1],tonic+k.steps[4],tonic]},solution=harmonizeTonal(args).solutions[0];if(!solution)continue;const r=proposeAutomaticSevenths({args,solution,degrees:[1,4]});for(const p of r.proposals){verify(p,args);count++}}assert.ok(count>=25);});
test('blocchi integrali impediscono aggiunte; errori esistenti e basso vuoto non vengono forzati',()=>{const solution=harmonizeTonal(base).solutions[0],locks=Object.fromEntries(solution.map((c,i)=>[i,Object.fromEntries(c.voices.map((n,v)=>[v,n]))]));assert.equal(proposeAutomaticSevenths({args:{...base,locks},solution,degrees:[1,4]}).proposals.length,0);const bad=structuredClone(solution);bad[2].voices[3]=bad[1].voices[3]+24;assert.equal(proposeAutomaticSevenths({args:base,solution:bad,degrees:[1,4]}).proposals.length,0);assert.match(proposeAutomaticSevenths({args:{...base,bass:[]},solution:[],degrees:[4]}).message,/Armonizza/);});
test('preparazione troppo breve viene esclusa',()=>{const args={...base,durations:[1,1,16,16]},solution=harmonizeTonal(base).solutions[0],r=proposeAutomaticSevenths({args,solution,degrees:[1]});assert.equal(r.proposals.length,0)});
