import test from 'node:test';import assert from 'node:assert/strict';
import {KEYS,harmonize,possibleAt,issues,label} from '../sito/public/app/engine.mjs';
import {proposeHarmonyEdit} from '../sito/public/app/actions.mjs';
import {expandHarmony,soundingNotes,tieLinks} from '../sito/public/app/harmonic-rhythm.mjs';
import {musicXML,midiBytes} from '../sito/public/app/notation.mjs';import {parseMusicXml} from '../sito/public/app/import.mjs';
import {scoreScene} from '../sito/public/app/pdf-view.mjs';import {scorePdf} from '../sito/public/app/pdf.mjs';
function example(key='Do maggiore',duration=64,bass=48){const args={key,bass:[bass],level:1,durations:[duration],seventhsEnabled:false,allowedSevenths:[4],meter:'4/4'};const solution=harmonize(args)[0];assert.ok(solution);const before=JSON.stringify({args,solution});const result=proposeHarmonyEdit({args,solution,index:0,kind:'cadence',cadenceType:'plagal'});assert.equal(JSON.stringify({args,solution}),before);assert.ok(result.proposals.length,result.message);return {args,p:result.proposals[0],events:[{start:0,midi:bass,kind:'note',duration:duration===64?'whole':'half'}]}}
test('Semibreve al basso invariata; sopra semiminima, semiminima, minima con I–IV64–I reali',()=>{const {p,events}=example();assert.deepEqual(p.bass,[48]);const x=expandHarmony(events,p.solution);assert.deepEqual(x.solutions.map(label),['I','IV64','I']);assert.deepEqual(x.events.map(e=>[e.start,e.duration,e._bassHeld]),[[0,'quarter',false],[16,'quarter',true],[32,'half',true]]);assert.ok(p.solution[0].segments.every(c=>c.voices[0]===48));x.solutions.forEach((c,i)=>assert.deepEqual(issues(x.solutions[i-1],c,'Do maggiore',3),[]));});
test('Plagale sul pedale in tutte le 30 tonalità, senza modificare le altezze scritte',()=>{for(const [key,k]of Object.entries(KEYS)){const bass=k.tonic-12;const {p}=example(key,64,bass);assert.deepEqual(p.bass,[bass]);const chords=p.solution[0].segments;assert.deepEqual(chords.map(c=>c.root),[0,3,0]);chords.forEach((c,i)=>assert.deepEqual(issues(chords[i-1],c,key,3),[],key))}});
test('IV64 è consentito solo nel profilo del pedale e richiede risoluzione discendente corretta',()=>{assert.ok(!possibleAt(48,'Do maggiore',3).some(c=>c.root===3&&c.inv===2));const {p}=example(),[a,b,c]=p.solution[0].segments;assert.ok(issues(b,{...c,voices:b.voices},'Do maggiore',3).includes('pedale_plagale_irrisolto'));assert.ok(issues({...b,pedalCadence:false},c,'Do maggiore',3).includes('quarta_sesta_irrisolta'));});
test('Screen/PDF: una sola semibreve al basso, nove note sopra e tre cifrature',async()=>{const {p,events}=example(),o={events,solutions:p.solution,key:'Do maggiore',meter:'4/4',measureCount:1,partSpacing:'late'};const records=scoreScene(o).pages.flatMap(p=>p.records),heads=records.filter(r=>r.tag==='notehead');assert.equal(heads.filter(r=>r.note.voice===0).length,1);assert.equal(heads.filter(r=>r.note.voice>0).length,9);assert.equal(heads.find(r=>r.note.voice===0).args[0].color,undefined);assert.deepEqual(records.filter(r=>r.tag==='chordText').map(r=>r.args[0]),['I','IV64','I']);assert.ok((await scorePdf(o)).length>1000)});
test('MusicXML: ritmi indipendenti e gradi su tutte le pulsazioni anche con parti strette',()=>{const {p,events}=example();for(const partSpacing of ['late','strette']){const xml=musicXML({events,solutions:p.solution,key:'Do maggiore',meter:'4/4',measureCount:1,partSpacing}),read=parseMusicXml(xml);assert.deepEqual(read.tracks[0].events.map(e=>[e.midi,e.duration,e.start]),[[48,'whole',0]]);assert.ok(read.tracks.some(t=>t.events.map(e=>e.duration).join(',')==='quarter,quarter,half'));assert.deepEqual([...xml.matchAll(/<words[^>]*>(.*?)<\/words>/g)].map(m=>m[1]),['I','DOM:','IV64','I']);assert.equal((xml.match(/<offset>/g)||[]).length,2)}});
test('Ascolto/MIDI: basso attaccato una volta per 4 tempi, tre accordi superiori con durate 1+1+2',()=>{const {p,events}=example(),sounds=soundingNotes(events,p.solution);assert.deepEqual(sounds.filter(s=>s.voice===0).map(s=>[s.start,s.length]),[[0,64]]);for(let v=1;v<=3;v++)assert.deepEqual(sounds.filter(s=>s.voice===v).map(s=>[s.start,s.length]),[[0,16],[16,16],[32,32]]);const midi=midiBytes({events,solutions:p.solution,bpm:84});assert.equal([...midi].filter(n=>n===0x90).length,1);assert.equal([...midi].filter(n=>n===0x91).length,3)});
test('Basso legato dopo la cadenza: mantenuto anche attraverso gli eventi delle voci superiori',()=>{const {p,events}=example();events[0].tieNext=true;events.push({start:64,midi:48,kind:'note',duration:'whole'});const sol=[...p.solution,{...p.solution[0],segments:undefined}],x=expandHarmony(events,sol);assert.ok(tieLinks(x.events,x.solutions).some(l=>l.from===0&&l.to===3&&l.voice===0));assert.deepEqual(soundingNotes(events,sol).filter(s=>s.voice===0).map(s=>s.length),[128]);const xml=musicXML({events,solutions:sol,key:'Do maggiore',meter:'4/4',measureCount:2});assert.ok(xml.includes('<tie type="start"/>'));assert.ok(xml.includes('<tie type="stop"/>'))});

test('Minima: stesso principio in proporzione, croma+croma+semiminima sul basso tenuto',()=>{const {p,events}=example('Do maggiore',32);assert.deepEqual(p.solution[0].segments.map(e=>e.duration),['eighth','eighth','quarter']);assert.deepEqual(soundingNotes(events,p.solution).filter(s=>s.voice===0).map(s=>s.length),[32])});
test('Basso non sulla tonica e voci bloccate incompatibili: non inventa una plagale valida',()=>{const args={key:'Do maggiore',bass:[55],level:1,durations:[64]},solution=harmonize(args)[0];const result=proposeHarmonyEdit({args,solution,index:0,kind:'cadence',cadenceType:'plagal'});assert.equal(result.proposals.length,0);assert.match(result.message,/tonica/);const e=example(),locked={...e.args,locks:{0:{1:64}}},fail=proposeHarmonyEdit({args:locked,solution:e.p.solution,index:0,kind:'cadence',cadenceType:'plagal'});assert.equal(fail.proposals.length,0)});

test('Blocchi delle singole pulsazioni della cadenza: rispettati al ricalcolo e conflitti segnalati',()=>{const e=example(),segments=e.p.solution[0].segments,rhythmLocks={0:Object.fromEntries(segments.map((s,i)=>[i,Object.fromEntries(s.voices.map((n,v)=>[v,n]))]))};const result=proposeHarmonyEdit({args:{...e.args,rhythmLocks},solution:e.p.solution,index:0,kind:'cadence',cadenceType:'plagal'});assert.ok(result.proposals.length,result.message);assert.deepEqual(result.proposals[0].solution[0].segments.map(s=>s.voices),segments.map(s=>s.voices));rhythmLocks[0][1][1]=61;const fail=proposeHarmonyEdit({args:{...e.args,rhythmLocks},solution:e.p.solution,index:0,kind:'cadence',cadenceType:'plagal'});assert.equal(fail.proposals.length,0);assert.ok(fail.message)});
