import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {initReferenceUI} from '../sito/public/app/reference-ui.mjs';
import {initMobileUI} from '../sito/public/app/mobile-ui.mjs';
class Node{constructor(id=''){this.id=id;this.children=[];this.attributes={};this.listeners={};this.open=false;this.hidden=false;this.parentNode=null}append(n){n.remove();this.children.push(n);n.parentNode=this}insertBefore(n,b){n.remove();const index=this.children.indexOf(b);assert.ok(index>=0);this.children.splice(index,0,n);n.parentNode=this}remove(){if(this.parentNode){this.parentNode.children.splice(this.parentNode.children.indexOf(this),1);this.parentNode=null}}setAttribute(k,v){this.attributes[k]=v}removeAttribute(k){delete this.attributes[k]}addEventListener(k,f){this.listeners[k]=f}querySelector(){return null}}
function fixture(matches=true){const ids=['app','referenceHeader','operationsToolbar','notationToolbar','scoreView','mobileControls','mobileMenu','mobileOptions','mobileMeasures','mobileWritingOptions','mobileEdit','mobileDelete','generateMenu','harmonizeMenu','modulationsPanel','tonicizationsPanel','chordMenu','featuresMenu','customizationMenu','importMenu','exportMenu','voiceSettings','sidebarTools','bassSettings','meterSettings','measureSettings','viewLayoutSettings','figuresOnly','valueShortcutSettings'],nodes=new Map(ids.map(id=>[id,new Node(id)])),$=id=>nodes.get(id),events={},document={getElementById:$,createComment:()=>new Node(),addEventListener:(k,f)=>events[k]=f};
 for(const id of ['referenceHeader','operationsToolbar','notationToolbar','scoreView','sidebarTools'])$('app').append($(id));
 for(const id of ['mobileControls','customizationMenu','importMenu','exportMenu'])$('referenceHeader').append($(id));for(const id of ['mobileMenu','mobileMeasures','mobileEdit','mobileDelete'])$('mobileControls').append($(id));$('mobileMenu').append($('mobileOptions'));$('mobileMeasures').append($('mobileWritingOptions'));
 for(const id of ['generateMenu','harmonizeMenu','modulationsPanel','tonicizationsPanel','chordMenu','featuresMenu'])$('operationsToolbar').append($(id));for(const id of ['voiceSettings','bassSettings','meterSettings','measureSettings'])$('sidebarTools').append($(id));$('sidebarTools').open=false;$('notationToolbar').append($('valueShortcutSettings'));$('scoreView').append($('viewLayoutSettings'));$('scoreView').append($('figuresOnly'));
 const original=new Map([...nodes].map(([id,n])=>[id,{parent:n.parentNode,children:[...n.children]}]));let editing=false,deletions=0;const media={matches,addEventListener:(k,f)=>media.change=f};const ui=initMobileUI(document,{media,getEditing:()=>editing,toggleWriting:()=>{editing=!editing;ui.sync(editing)},removeSelection:()=>deletions++});return{$,ui,media,events,original,get deletions(){return deletions}};
}
test('mobile: tutte le funzioni si spostano nel menu mantenendo valori e handler',()=>{const f=fixture();for(const id of ['generateMenu','harmonizeMenu','modulationsPanel','tonicizationsPanel','chordMenu','featuresMenu','customizationMenu','importMenu','exportMenu','voiceSettings','viewLayoutSettings','figuresOnly','valueShortcutSettings'])assert.equal(f.$(id).parentNode,f.$('mobileOptions'),id);for(const id of ['bassSettings','meterSettings','measureSettings'])assert.equal(f.$(id).parentNode,f.$('mobileWritingOptions'));assert.equal(f.$('sidebarTools').open,false);f.$('generateMenu').value='Re minore';let clicked=false;f.$('generateMenu').onclick=()=>clicked=true;f.ui.layout();f.$('generateMenu').onclick();assert.ok(clicked);assert.equal(f.$('generateMenu').value,'Re minore');assert.equal(f.$('app').attributes['data-mobile-workspace'],'true')});
test('Modifica cambia modalità, chiude i menu e rende disponibili solo gli strumenti di scrittura',()=>{const f=fixture();assert.equal(f.$('mobileMenu').hidden,false);assert.equal(f.$('mobileMeasures').hidden,true);f.$('mobileMenu').open=true;f.$('mobileEdit').onclick();assert.equal(f.$('app').attributes['data-mobile-edit'],'true');assert.equal(f.$('mobileMenu').hidden,true);assert.equal(f.$('mobileMenu').open,false);assert.equal(f.$('mobileMeasures').hidden,false);assert.equal(f.$('mobileEdit').attributes['aria-pressed'],'true');f.$('mobileDelete').onclick();assert.equal(f.deletions,1);f.$('mobileMeasures').open=true;f.$('mobileEdit').onclick();assert.equal(f.$('mobileMeasures').open,false);assert.equal(f.$('mobileMenu').hidden,false);assert.equal(f.$('mobileEdit').attributes['aria-pressed'],'false')});
test('desktop dopo mobile: ripristino esatto di ordine e genitori senza duplicare i controlli',()=>{const f=fixture();f.media.matches=false;f.media.change();for(const [id,old]of f.original){assert.equal(f.$(id).parentNode,old.parent,id);assert.deepEqual(f.$(id).children,old.children,id)}assert.equal(f.$('app').attributes['data-mobile-workspace'],undefined);f.media.matches=true;f.media.change();assert.equal(f.$('mobileOptions').children.length,13)});
test('schermo intero e chiusura dei menu: gli stessi controlli rimangono accessibili',()=>{const f=fixture();f.$('scoreView').append(f.$('referenceHeader'));assert.equal(f.$('mobileControls').parentNode,f.$('referenceHeader'));assert.equal(f.$('modulationsPanel').parentNode,f.$('mobileOptions'));f.$('mobileMenu').open=true;f.events.keydown({key:'Escape'});assert.equal(f.$('mobileMenu').open,false);f.$('mobileMenu').open=true;f.events.pointerdown({target:{closest:()=>null}});assert.equal(f.$('mobileMenu').open,false);f.$('mobileMenu').open=true;f.$('mobileOptions').listeners.click({target:{closest:()=>true}});assert.equal(f.$('mobileMenu').open,false)});
test('mobile CSS: viewport unico, strumenti touch, partitura scorrevole e drawer opaco',()=>{const css=fs.readFileSync(new URL('../sito/public/app/reference-layout.css',import.meta.url),'utf8'),html=fs.readFileSync(new URL('../sito/public/harmony.html',import.meta.url),'utf8');assert.match(css,/data-mobile-workspace.*height:100dvh/);assert.match(css,/data-mobile-edit="false".*#notationToolbar\{display:none!important/);assert.match(css,/data-mobile-edit="true".*#operationsToolbar\{display:none/);assert.match(css,/touch-action:pan-x pan-y/);assert.match(css,/#mobileWritingOptions\{position:fixed!important/);for(const id of ['mobileEdit','mobileMenu','mobileMeasures','mobileDelete'])assert.ok(html.includes('id="'+id+'"'))});

test('aprire una funzione non chiude il menu mobile che la contiene',()=>{const menu=new Node('mobileMenu'),measures=new Node('mobileMeasures'),generate=new Node('generateMenu'),custom=new Node('customizationMenu');initReferenceUI({querySelectorAll:selector=>selector.includes('operationsToolbar')?[menu,measures,generate,custom]:[],addEventListener(){}});menu.open=true;generate.open=true;custom.open=true;generate.listeners.toggle();assert.equal(menu.open,true);assert.equal(custom.open,false);assert.equal(generate.open,true)});

test('un ricalcolo in scrittura non chiude il pannello Battute',()=>{const f=fixture();f.$('mobileEdit').onclick();f.$('mobileMeasures').open=true;f.ui.sync(true);assert.equal(f.$('mobileMeasures').open,true);assert.equal(f.$('measureSettings').parentNode,f.$('mobileWritingOptions'))});
