import test from 'node:test';import assert from 'node:assert/strict';
import {inputKind,pastedFile,recognizeScan,serviceUrl,MAX_SCAN_BYTES}from'../sito/public/app/omr-client.mjs';
import {inspectImport,reviewMidi}from'../sito/public/app/import-review.mjs';

const id='abc123'.padEnd(32,'0'),file=new Blob(['%PDF-example'],{type:'application/pdf'});file.name='basso.pdf';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
test('formati e incolla riconoscono spartiti, PDF e immagini senza confondere testo',()=>{for(const name of ['x.mscz','x.mscx','x.mxl','x.musicxml'])assert.equal(inputKind({name}),'score');for(const name of ['x.PDF','x.JPEG','x.webp'])assert.equal(inputKind({name}),'scan');assert.throws(()=>inputKind({name:'x.exe'}));assert.equal(pastedFile({files:[file]}),file);assert.equal(pastedFile({items:[{kind:'file',getAsFile:()=>({type:'image/png'})}]}).type,'image/png');assert.equal(pastedFile({files:[],items:[]}),null);});
test('OMR segue coda e avanzamento fino al vero risultato binario',async()=>{const calls=[],messages=[];let poll=0;const result=await recognizeScan(file,{delay:async()=>{},onProgress:m=>messages.push(m),fetchImpl:async(url,opt)=>{calls.push([url,opt]);if(opt.method==='POST')return json({id});if(url.includes('result='))return new Response('MXL');return json({status:++poll===1?'queued':'done',message:'Lettura…',warnings:['Controlla ritmi']});}});assert.equal(result.name,'riconosciuto.mxl');assert.equal(result.size,3);assert.deepEqual(result.warnings,['Controlla ritmi']);assert.equal(calls.length,4);assert.equal(calls[0][1].body,file);assert.ok(messages.includes('Lettura…'));});
test('OMR rifiuta errori, file grandi, risposte false e timeout senza inventare note',async()=>{await assert.rejects(recognizeScan({...file,name:'x.pdf',size:MAX_SCAN_BYTES+1}),/4 MB/);await assert.rejects(recognizeScan(file,{fetchImpl:async()=>json({error:'Non collegato'},503)}),/Non collegato/);await assert.rejects(recognizeScan(file,{fetchImpl:async()=>json({id:'bad'})}),/non valida/);await assert.rejects(recognizeScan(file,{maxWaitMs:-1,fetchImpl:async(u,o)=>o.method==='POST'?json({id}):json({status:'running'})}),/troppo tempo/);await assert.rejects(recognizeScan(file,{fetchImpl:async(u,o)=>o.method==='POST'?json({id}):json({status:'error',message:'Foto sfocata'})}),/Foto sfocata/);assert.throws(()=>serviceUrl('javascript:bad'),/non valido/);});
test('annullamento ferma il job remoto e non consegna il risultato',async()=>{const control=new AbortController(),calls=[];await assert.rejects(recognizeScan(file,{signal:control.signal,delay:async()=>control.abort(),fetchImpl:async(u,o)=>{calls.push(o.method||'GET');return o.method==='POST'?json({id}):json({status:'running'})}}),e=>e.name==='AbortError');assert.ok(calls.includes('DELETE'));});
const event=(start=0,midi=48,duration='quarter')=>({start,kind:'note',midi,duration});
test('controllo importazione mantiene altezze, punti e legature e segnala battute incomplete',()=>{const data=inspectImport({events:[{...event(),dotted:true},{...event(24),duration:'eighth',tieNext:true},event(32)],key:'Do maggiore',meter:'4/4'});assert.equal(data.events[0].dotted,true);assert.equal(data.events[1].tieNext,true);assert.match(data.warnings[0],/incomplete/);assert.equal(reviewMidi({letter:'Fa',alter:1,octave:3}),54);assert.equal(reviewMidi({letter:'Si',alter:-1,octave:2}),46);});
test('controllo importazione blocca sovrapposizioni, metriche, legature e altezze non valide',()=>{const check=events=>inspectImport({events,key:'Do maggiore',meter:'4/4'});assert.throws(()=>check([event(),event(8)]),/sovrapposte/);assert.throws(()=>check([{...event(),tieNext:true},event(16,50)]),/Legatura/);assert.throws(()=>check([event(60)]),/metrica/);assert.throws(()=>check([event(0,NaN)]),/altezza/);assert.throws(()=>reviewMidi({letter:'Fa',alter:3,octave:3}),/non valida/);});
test('errori di rete e pagine HTML sono spiegati in italiano',async()=>{await assert.rejects(recognizeScan(file,{fetchImpl:async()=>{throw new TypeError('Failed to fetch')}}),/Impossibile raggiungere/);await assert.rejects(recognizeScan(file,{fetchImpl:async()=>new Response('<html/>')}),/risposta OMR/);});
