import test from 'node:test';import assert from 'node:assert/strict';
import {scoreScene,engravedSvg} from '../sito/public/app/pdf-view.mjs';import {scoreLayout,PDF_ENGRAVING} from '../sito/public/app/pdf.mjs';import {harmonize}from'../sito/public/app/engine.mjs';
const events=[48,53,55,48,48,50,55,48].map((midi,i)=>({midi,start:i*32,duration:'half',kind:'note'})),solutions=harmonize({bass:events.map(e=>e.midi),key:'Do maggiore',level:3})[0],options={events,solutions,key:'Do maggiore',meter:'2/2',measureCount:8,partSpacing:'late'};
function node(tag,a={},text=''){return {tagName:tag,attributes:{...a},children:[],style:{},textContent:String(text),setAttribute(k,v){this.attributes[k]=String(v)},append(n){this.children.push(n)}};}
test('lo schermo usa la medesima incisione del PDF: 4 battute per sistema e pause nei due righi',()=>{const s=scoreScene(options),r=s.pages.flatMap(p=>p.records);assert.equal(scoreLayout(options).systems.length,2);assert.deepEqual([...new Set(r.filter(r=>r.system).map(r=>r.system.index))],[0,1]);const heads=r.filter(r=>r.method==='drawEllipse');assert.equal(heads.length,32);assert.ok(heads.every(r=>r.args[0].xScale===PDF_ENGRAVING.headRx&&r.args[0].yScale===PDF_ENGRAVING.headRy));const rests=r.filter(r=>r.tag?.startsWith('restGlyph'));assert.equal(rests.length,8);assert.deepEqual([...new Set(rests.map(r=>r.measure.number))],[5,6,7,8]);});
test('secondo sistema separato, numeri di battuta e metrica corrispondono al PDF',()=>{const v=engravedSvg(options,node),labels=v.svg.children.filter(n=>n.attributes.class==='barLabel');assert.deepEqual(labels.map(n=>n.textContent),['1','2','3','4','5','6','7','8']);assert.equal(v.svg.children.filter(n=>n.attributes.class==='timeSignature').length,4);const lines=v.svg.children.filter(n=>n.attributes.class==='staffLine');const first=lines.find(n=>n.attributes['data-system']==='0'),second=lines.find(n=>n.attributes['data-system']==='1');assert.ok(second.attributes.y1-first.attributes.y1>200);assert.equal(v.groups.length,32);assert.equal(v.measures.length,8);});
test('tutte le figure del PDF, comprese le note brevi e le legature, restano vettoriali e selezionabili',()=>{const e=events.slice(0,4).map((e,i)=>({...e,start:i*8,duration:'eighth',tieNext:i===0,midi:i===1?48:e.midi})),v=engravedSvg({...options,events:e,solutions:null,measureCount:1,meter:'4/4'},node);assert.ok(v.groups.every(g=>g.children.some(n=>n.tagName==='ellipse')));assert.ok(v.groups.some(g=>g.children.some(n=>n.attributes.class==='flag')));assert.ok(v.svg.children.some(n=>n.attributes.class==='tieArc'));assert.equal(v.svg.attributes['data-renderer'],'pdf-shared-v3');assert.ok(Number(v.svg.attributes['data-staff-space'])>=16);});
test('vista continua non comprime un basso lungo e solo cifrature conserva i gradi senza note',()=>{const normal=engravedSvg({...options,measureCount:4},node),long=engravedSvg({...options,continuous:true},node);assert.ok(parseFloat(long.svg.style.width)>parseFloat(normal.svg.style.width));assert.equal(long.systems.length,1);const figures=engravedSvg({...options,figuresOnly:true},node);assert.equal(figures.groups.length,0);assert.equal(figures.svg.children.filter(n=>n.attributes.class==='chordText').length,8);});
test('Basso solo: riduce il margine vuoto ma conserva note alte e tutti i gambi nella vista',()=>{for(const midi of [0,28,43,62,72,127]){const v=engravedSvg({events:[{midi,start:0,duration:'quarter',kind:'note'}],key:'Do maggiore',meter:'4/4',measureCount:1},node),box=v.svg.attributes.viewBox.split(' ').map(Number),top=box[1],bottom=top+box[3];for(const g of v.groups)for(const n of g.children)for(const a of ['cy','y1','y2'])if(n.attributes[a]!==undefined){const y=Number(n.attributes[a]);assert.ok(y>=top&&y<=bottom,`${midi}: ${a} ${y} fuori ${top}..${bottom}`)}}});

test('Minime, semibrevi e brevi: il centro vuoto della testa ha una superficie cliccabile trasparente',()=>{for(const duration of ['half','whole','breve']){const v=engravedSvg({events:[{midi:48,start:0,duration,kind:'note'}],key:'Do maggiore',meter:duration==='breve'?'8/4':'4/4',measureCount:2},node);for(const g of v.groups){const head=g.children.find(n=>n.tagName==='ellipse'),hit=g.children.find(n=>n.attributes.class==='noteHit');assert.ok(hit);assert.equal(hit.attributes.fill,'transparent');assert.equal(hit.attributes['pointer-events'],'all');assert.ok(Number(hit.attributes.x)<head.attributes.cx);assert.ok(Number(hit.attributes.x)+Number(hit.attributes.width)>head.attributes.cx);assert.equal(head.attributes.fill,'none')}}});
