import test from 'node:test';import assert from 'node:assert/strict';
import {staffY,staffStep,ledgerLines,dotY,HEAD,headOffsets,CLEFS,STAFF,SCREEN_SCALE} from '../sito/public/app/staff-geometry.mjs';
import {fillMeasures,eventUnits} from '../sito/public/app/notation.mjs';
test('chiave di basso: Sol2 Si2 Re3 Fa3 La3 sui cinque righi',()=>{assert.deepEqual([18,20,22,24,26].map(n=>staffY(n,true)),[274,264,254,244,234].map(y=>y-142+67*10/7));});
test('chiave di violino: Mi4 Sol4 Si4 Re5 Fa5 sui cinque righi',()=>{assert.deepEqual([30,32,34,36,38].map(n=>staffY(n,false)),[132,122,112,102,92]);});
test('ogni spazio e rigo torna alla stessa nota al click, anche fuori pentagramma',()=>{for(const lower of [false,true])for(let n=9;n<48;n++)assert.equal(staffStep(staffY(n,lower),lower),n);});
test('teste ovali non invadono i righi adiacenti e punti sui righi salgono allo spazio',()=>{const verticalRadius=Math.sqrt((HEAD.rx*Math.sin(20*Math.PI/180))**2+(HEAD.ry*Math.cos(20*Math.PI/180))**2);assert.ok(verticalRadius+1.143/2<5);assert.equal(dotY(STAFF.lower.bottom-20,true),STAFF.lower.bottom-25);assert.equal(dotY(STAFF.lower.bottom-15,true),STAFF.lower.bottom-15);});
test('tagli addizionali solo su righi esterni completi',()=>{assert.deepEqual(ledgerLines(STAFF.lower.bottom+5,true),[]);assert.deepEqual(ledgerLines(STAFF.lower.bottom+10,true),[STAFF.lower.bottom+10]);assert.deepEqual(ledgerLines(STAFF.lower.bottom+25,true),[STAFF.lower.bottom+10,STAFF.lower.bottom+20]);assert.deepEqual(ledgerLines(77,false),[82]);});
test('voci sullo stesso rigo a distanza di seconda restano distinguibili',()=>{assert.deepEqual(headOffsets([254,259,112,107],[true,true,false,false]),[12,0,12,0]);assert.deepEqual(headOffsets([254,244,112,92],[true,true,false,false]),[0,0,0,0]);});
test('punti della chiave di basso abbracciano il quarto rigo e spirale sul Sol4',()=>{const c=CLEFS.bass;assert.ok(Math.abs(c.y-644*c.scale-(STAFF.lower.top+10))<1e-9);assert.ok(Math.abs(CLEFS.treble.y-254*CLEFS.treble.scale-122)<1e-9);});
test('tutte le metriche disponibili hanno esattamente la durata prevista in ogni battuta',()=>{for(const meter of ['2/4','3/4','4/4','6/8','3/2','2/2','8/4']){const [n,d]=meter.split('/').map(Number),bar=n*64/d;const events=[{kind:'note',duration:'eighth',start:0,midi:43},{kind:'rest',duration:'eighth',start:8},{kind:'note',duration:'quarter',start:16,midi:48}];const filled=fillMeasures(events,meter,3);for(let m=0;m<3;m++)assert.equal(filled.filter(e=>e.start>=m*bar&&e.start<(m+1)*bar).reduce((s,e)=>s+eventUnits(e),0),bar,meter);}});

test('scala su schermo leggibile e proporzioni delle teste identiche al PDF',()=>{assert.ok(STAFF.space*SCREEN_SCALE>=16);assert.equal(HEAD.rx/(STAFF.space/7),4);assert.equal(HEAD.ry/(STAFF.space/7),2.7);assert.ok(Math.abs((STAFF.lower.top-STAFF.upper.top)/STAFF.space-67/7)<1e-9);});
