import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync(new URL('../pannello/public/index.html',import.meta.url),'utf8'),script=html.match(/<script type="module">([\s\S]*?)<\/script>/)[1];
class Element{constructor(tag='div',text=''){this.tagName=tag.toUpperCase();this.textContent=text;this.children=[];this.dataset={};this.value='';this.open=false;this.hidden=false;this.disabled=false;}append(...c){this.children.push(...c)}replaceChildren(...c){this.children=c}querySelectorAll(q){const all=this.children.flatMap(c=>[c,...c.querySelectorAll?.('*')||[]]);return q==='*'?all:all.filter(c=>q==='details[open]'&&c.tagName==='DETAILS'&&c.open)}querySelector(q){return this.querySelectorAll(q)[0]||null}}
function setup(fetch){const elements=new Map(),timers=[],redirects=[];const el=id=>{if(!elements.has(id))elements.set(id,new Element());return elements.get(id)},context=vm.createContext({document:{getElementById:el,createElement:tag=>new Element(tag),activeElement:null},fetch,AbortSignal,Date,JSON,console,confirm:()=>true,location:{replace:s=>redirects.push(s)},navigator:{clipboard:{writeText:async()=>{}}},setInterval:fn=>{timers.push(fn);return timers.length}});vm.runInContext(script.replace(";load().catch(failure);setInterval", ";globalThis.ready=load().catch(failure);setInterval"),context);return {context,el,timers,redirects}}
const empty=()=>({licenses:[],devices:[],sessions:[],ips:[],actor:'owner@example.com',server_time:Math.floor(Date.now()/1000)});
test('Pannello: script valido e copia pubblicata uguale al sorgente',()=>{new vm.Script(script);assert.equal(html,fs.readFileSync(new URL('../server/admin.html',import.meta.url),'utf8'))});
test('Pannello: avvio, campi creazione, key mostrata e elenco renderizzato',async()=>{let data=empty();const requests=[],ui=setup(async(url,o={})=>{requests.push({url,...o});if(o.method==='POST'){const b=JSON.parse(o.body);data.licenses=[{id:'k1',...b,enabled:1,expires:null,created:data.server_time}];return Response.json({id:'k1',key:'AR-TEST-KEY'}, {status:201})}return Response.json(data)});await ui.context.ready;assert.equal(ui.el('identity').textContent,'Amministratore: owner@example.com');const labels=ui.el('create').children.filter(c=>c.tagName==='LABEL');assert.equal(labels.length,9);assert.equal(ui.el('keys').children[0].textContent,'Nessuna key: creane una sopra.');labels.find(l=>l.children[0].name==='label').children[0].value='Prova';await ui.el('create').onsubmit({preventDefault(){}});assert.equal(ui.el('newKey').textContent,'AR-TEST-KEY');assert.equal(ui.el('keyBox').hidden,false);assert.equal(requests.filter(r=>r.method==='POST').length,1);assert.match(ui.el('keys').children[0].children[0].textContent,/Prova.*Autorizzata/);assert.equal(ui.el('message').textContent,'Impostazioni salvate.')});
test('Pannello: sessione scaduta torna al login, rete e risposte errate danno errore leggibile',async()=>{const expired=setup(async()=>Response.json({error:'Scaduta'},{status:401}));await expired.context.ready;assert.deepEqual(expired.redirects,['/login']);for(const fetch of [async()=>{throw Error('Connessione interrotta')},async()=>new Response('<html>Errore</html>')]){const ui=setup(fetch);await ui.context.ready;assert.equal(ui.el('identity').textContent,'Caricamento non riuscito');assert.ok(ui.el('message').textContent);assert.notEqual(ui.el('identity').textContent,'Verifica identità…')}});
test('Pannello: logout invia POST e rimanda al login',async()=>{const requests=[],ui=setup(async(url,o={})=>{requests.push({url,...o});return Response.json(url.endsWith('/keys')?empty():{ok:true})});await ui.context.ready;await ui.el('logout').onclick();assert.equal(requests.at(-1).url,'/api/admin/logout');assert.equal(requests.at(-1).method,'POST');assert.deepEqual(ui.redirects,['/login'])});

test('Pannello: elimina key solo dopo conferma e aggiorna elenco',async()=>{let data={...empty(),licenses:[{id:'k1',label:'Test',enabled:1,max_devices:3,max_sessions:3,ip_mode:'any',device_mode:'any'}]};const posts=[],ui=setup(async(url,o={})=>{if(o.method==='POST'){posts.push({url,body:JSON.parse(o.body)});data={...empty()};return Response.json({ok:true})}return Response.json(data)});await ui.context.ready;const button=ui.el('keys').querySelectorAll('*').find(e=>e.tagName==='BUTTON'&&e.textContent==='Elimina key');assert.ok(button);ui.context.confirm=()=>false;await button.onclick();assert.equal(posts.length,0);ui.context.confirm=()=>true;await button.onclick();assert.deepEqual(posts,[{url:'/api/admin/keys/k1/delete',body:{confirm:true}}]);assert.equal(ui.el('keys').children[0].textContent,'Nessuna key: creane una sopra.')});
