import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {initReferenceUI} from '../sito/public/app/reference-ui.mjs';
const html=fs.readFileSync(new URL('../sito/public/harmony.html',import.meta.url),'utf8'),baseline=JSON.parse(fs.readFileSync(new URL('./fixtures/interface-before.json',import.meta.url),'utf8'));
test('Nuovo design conserva tutti i 174 controlli originali senza duplicare ID, incluse importazioni e correzioni',()=>{const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);assert.equal(Object.keys(baseline).length,174);for(const [id,tag] of Object.entries(baseline))assert.match(html,new RegExp('<'+tag+'\\b[^>]*\\bid="'+id+'"'),id);});
test('Sidebar solo per scrittura, note e pause nella barra superiore, funzioni ed elenchi nei menu centrali',()=>{const sidebar=html.match(/<aside\b[\s\S]*?<\/aside>/)[0];for(const id of ['key','meter','partSpacing','addMeasure'])assert.ok(sidebar.includes('id="'+id+'"'));for(const id of ['noteTools','restTools','generatorControls','solve','modulationsPanel','seventhsPanel','tonalEvents','exportMenu','customizationMenu'])assert.ok(!sidebar.includes('id="'+id+'"'),id);for(const id of ['generateMenu','harmonizeMenu','modulationsPanel','tonicizationsPanel','chordMenu','featuresMenu'])assert.ok(html.includes('id="'+id+'"'));assert.equal((html.match(/data-open-section="tonalListPanel"/g)||[]).length,2);assert.ok(html.indexOf('id="noteTools"')<html.indexOf('<main>'));assert.ok(html.indexOf('id="restTools"')<html.indexOf('<main>'));});
test('Menu: esclusione reciproca, collegamento elenco ed Escape; i controlli rimangono gli stessi oggetti',()=>{const menus=['mod','tonic','featuresMenu'].map(id=>({id,open:false,addEventListener(k,f){this[k]=f}})),section={open:false},link={dataset:{openMenu:'featuresMenu',openSection:'tonalListPanel'}},listeners={},doc={querySelectorAll:s=>s.includes('data-open')?[link]:menus,getElementById:id=>id==='tonalListPanel'?section:menus.find(m=>m.id===id),addEventListener:(k,f)=>listeners[k]=f};initReferenceUI(doc);menus[0].open=true;menus[0].toggle();assert.equal(menus[0].open,true);menus[1].open=true;menus[1].toggle();assert.equal(menus[0].open,false);link.onclick();assert.equal(menus[2].open,true);assert.equal(section.open,true);assert.equal(menus[1].open,false);listeners.keydown({key:'Escape'});assert.ok(menus.every(m=>!m.open));});
test('Offline incorpora anche il nuovo stylesheet e mantiene i controlli originali',()=>{const offline=fs.readFileSync(new URL('../offline/index.html',import.meta.url),'utf8');assert.ok(!offline.includes('<style data-offline='));assert.ok(offline.includes('.referenceHeader'));for(const id of Object.keys(baseline))assert.ok(offline.includes('id="'+id+'"'),id);});

test('Importa offre MuseScore e MusicXML, elimina il riconoscimento e Personalizza ha uno sfondo opaco',()=>{assert.match(html,/accept="\.mscz,\.mscx,\.musicxml,\.xml,\.mxl"/);assert.match(html,/id="pasteImage" hidden disabled/);const css=fs.readFileSync(new URL('../sito/public/app/reference-layout.css',import.meta.url),'utf8');assert.match(css,/\.referenceHeader \.toolDrawer>\.drawerContent\{background:var\(--ui-field\)!important/);const js=fs.readFileSync(new URL('../sito/public/app/import-ui.mjs',import.meta.url),'utf8');assert.ok(!js.includes('recognizeScan'));assert.ok(!js.includes('clipboard.read'));});

test('Importa, Esporta e Personalizza stanno sopra le barre, anche nella versione offline',()=>{
 const css=fs.readFileSync(new URL('../sito/public/app/reference-layout.css',import.meta.url),'utf8'),offline=fs.readFileSync(new URL('../offline/index.html',import.meta.url),'utf8');for(const source of [css,offline]){assert.match(source,/#referenceHeader\{position:relative!important;z-index:200!important;overflow:visible!important\}/);assert.match(source,/#referenceHeader \.fileTools>\.toolDrawer>\.drawerContent\{z-index:210!important\}/)}const operationsZ=Number(css.match(/\.operationsToolbar\{[^}]*z-index:(\d+)/)[1]);assert.ok(200>operationsZ);assert.match(html,/id="importScore"[^>]*>Importa basso/);for(const id of ['musicxml','midi','pdf'])assert.match(html,new RegExp('<button id="'+id+'"'));
});
