import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {harmonize} from '../sito/public/app/engine.mjs';
const html=fs.readFileSync(new URL('../offline/index.html',import.meta.url),'utf8'),scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
class Element{constructor(tag='div'){this.tagName=tag;this.children=[];this.attributes={};this.style={};this.value='';this.textContent='';this.className='';this.inert=false}get options(){return this.children}setAttribute(k,v){this.attributes[k]=String(v)}getAttribute(k){return this.attributes[k]}append(...c){this.children.push(...c)}prepend(...c){this.children.unshift(...c)}click(){this.onclick?.()}replaceChildren(...c){this.children=c}add(o){this.children.push(o)}cloneNode(){return new Element(this.tagName)}querySelectorAll(){return []}createSVGPoint(){return{x:0,y:0,matrixTransform(){return{x:this.x,y:this.y}}}}getScreenCTM(){return{inverse(){return{}}}}}
function boot(saved){const els=new Map(),store=new Map([['armonizza-v2',JSON.stringify(saved)],['armonizza-paper-workspace-v1','1']]),el=id=>{if(!els.has(id))els.set(id,new Element());return els.get(id)},context=vm.createContext({document:{getElementById:el,createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),createTextNode:text=>({textContent:text}),addEventListener(){}},Option:class{constructor(t,v){this.textContent=t;this.value=v}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},structuredClone,TextEncoder,TextDecoder,Blob,URL,setTimeout,clearTimeout,AbortController,console,addEventListener(){},print(){}});context.window=context;context.self=context;for(const s of scripts)vm.runInContext(s,context);return{el,store}}
const event={kind:'note',midi:48,start:0,duration:'whole'},base={key:'Do maggiore',meter:'4/4',scoreLayout:'paged',mode:'write',level:1,measureCount:4,events:[event],maxModulations:2};
test('Avvio reale del bundle offline: esercizio manuale ricompare esattamente, con indicazione di verifica',()=>{const solution=harmonize({bass:[48],key:'Do maggiore',level:1})[0];solution[0].voices[1]=57;const {el}=boot({...base,manualSolution:solution});assert.match(el('resultSub').textContent,/Esercizio modificato/);const tenor=el('staff').children[0].children.find(n=>n.attributes.class==='noteTarget'&&n.attributes['data-voice']==='1');tenor.onclick();assert.equal(el('noteEditor').children[0].children[0].value,'57');assert.equal(el('maxModulations').value,'2')});
test('Avvio: 1/32 e 1/64 si conservano, con basso corretto e senza cambiare in 4/4',()=>{for(const [meter,duration]of[['1/32','32nd'],['1/64','64th']]){const {el}=boot({...base,meter,events:[{...event,duration}],deferHarmony:true});assert.equal(el('meter').value,meter);assert.equal(el('bassEditor').children.length,1);assert.match(el('bassEditor').children[0].textContent,/Do3/);assert.equal(el('resultCount').textContent,'0 soluzioni')}});
test('Dati salvati incoerenti non bloccano l’avvio: recupero di uno spartito renderizzabile',()=>{const {el}=boot({...base,meter:'1/64',events:[event],manualSolution:[{voices:[48,NaN,72,74]}]});assert.equal(el('meter').value,'4/4');assert.ok(el('staff').children.length);assert.equal(typeof el('clearAll').onclick,'function')});

test('una o due battute salvate restano tali al riavvio: le battute eliminate non ricompaiono',()=>{for(const count of [1,2]){const {el}=boot({...base,events:[],measureCount:count,deferHarmony:true});assert.match(el('measureRange').textContent,new RegExp('di '+count+'$'));assert.equal(el('measureToDelete').max,count)}});
