const enc=new TextEncoder();
export const digest=async s=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s)))).map(n=>n.toString(16).padStart(2,'0')).join('');
const token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32))).map(n=>n.toString(16).padStart(2,'0')).join('');
const now=()=>Math.floor(Date.now()/1000);
export const REMEMBER_SECONDS=365*86400;
const json=(o,status=200)=>new Response(JSON.stringify(o),{status,headers:{'Content-Type':'application/json; charset=utf-8'}});
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
const cookie=(name,value,age)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${age}`;
const cookies=req=>Object.fromEntries((req.headers.get('cookie')||'').split(';').map(s=>s.trim().split('=')));
const stmt=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
export function normalizeIP(s){if(typeof s!=='string'||s.length>64)fail('IP non valido.');if(s.includes(':')){try{return new URL(`http://[${s}]/`).hostname.slice(1,-1).toLowerCase()}catch{fail('IP non valido.')}}if(!/^\d{1,3}(\.\d{1,3}){3}$/.test(s)||s.split('.').some(p=>Number(p)>255||String(Number(p))!==p))fail('IP non valido.');return s;}
const ipOf=req=>normalizeIP(req.headers.get('cf-connecting-ip')||'');
export function options(b){const max_devices=Number(b.max_devices??3),max_sessions=Number(b.max_sessions??3);if(!Number.isInteger(max_devices)||max_devices<1||max_devices>100||!Number.isInteger(max_sessions)||max_sessions<1||max_sessions>100)fail('Limiti: interi da 1 a 100.');const ip_mode=b.ip_mode||'any',device_mode=b.device_mode||'any';if(!['any','first','fixed'].includes(ip_mode)||!['any','first','fixed'].includes(device_mode))fail('Vincolo non valido.');const allowed_ip=ip_mode==='fixed'?normalizeIP(b.allowed_ip):null,allowed_device=device_mode==='fixed'?String(b.allowed_device||''):null;if(device_mode==='fixed'&&!/^[a-f0-9-]{36}$/.test(allowed_device))fail('Seleziona un dispositivo già registrato.');const expires=b.expires?Math.floor(new Date(b.expires).getTime()/1000):null;if(expires!==null&&(!Number.isFinite(expires)||expires<0))fail('Scadenza non valida.');const label=String(b.label||'Nuova key').trim().slice(0,100);return {label,enabled:b.enabled===false?0:1,expires,max_devices,max_sessions,ip_mode,allowed_ip,device_mode,allowed_device};}
async function bounded(req,limit){if(Number(req.headers.get('content-length'))>limit)fail('Richiesta troppo grande.',413);const reader=req.body?.getReader();if(!reader)return new Uint8Array();const chunks=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>limit){await reader.cancel();fail('Richiesta troppo grande.',413)}chunks.push(value)}const all=new Uint8Array(size);let offset=0;for(const c of chunks){all.set(c,offset);offset+=c.byteLength}return all;}
async function body(req){const text=new TextDecoder().decode(await bounded(req,16000));try{return JSON.parse(text)}catch{fail('JSON non valido.')}}
function origin(req){if(req.headers.get('origin')!==new URL(req.url).origin)fail('Origine non autorizzata.',403);if(req.headers.get('sec-fetch-site')==='cross-site')fail('Richiesta non autorizzata.',403);}
export async function validateSession(req,env){const c=cookies(req);if(!/^[a-f0-9]{64}$/.test(c['__Host-ar-session']||'')||!/^[a-f0-9]{64}$/.test(c['__Host-ar-device']||''))return null;const s=await stmt(env,`SELECT s.*,l.enabled AS key_enabled,l.expires AS key_expires,l.ip_mode,l.allowed_ip,l.device_mode,l.allowed_device,d.enabled AS device_enabled,d.proof FROM sessions s JOIN licenses l ON l.id=s.key_id JOIN devices d ON d.id=s.device_id WHERE s.hash=?`,await digest(c['__Host-ar-session'])).first();if(!s||s.revoked||!s.key_enabled||!s.device_enabled||s.expires<=now()||s.key_expires&&s.key_expires<=now()||s.proof!==await digest(c['__Host-ar-device']))return null;const ip=ipOf(req);if(s.ip_mode!=='any'&&s.allowed_ip!==ip||s.device_mode!=='any'&&s.allowed_device!==s.device_id)return null;if(s.expires<now()+REMEMBER_SECONDS-86400){s.expires=now()+REMEMBER_SECONDS;await stmt(env,'UPDATE sessions SET expires=? WHERE id=? AND revoked=0',s.expires,s.id).run();s.refreshCookies=true;}if(s.seen<now()-60||s.ip!==ip){await env.DB.batch([stmt(env,'UPDATE sessions SET seen=?,ip=? WHERE id=?',now(),ip,s.id),stmt(env,'INSERT INTO ip_history VALUES(?,?,?,?) ON CONFLICT(session_id,ip) DO UPDATE SET last_seen=excluded.last_seen',s.id,ip,now(),now())]);}return s;}
export async function login(req,env){origin(req);const ip=ipOf(req),minute=Math.floor(now()/60),iph=await digest(ip);const rate=await env.DB.batch([stmt(env,'INSERT INTO attempts VALUES(?,?,1) ON CONFLICT(ip_hash,minute) DO UPDATE SET count=count+1',iph,minute),stmt(env,'SELECT count FROM attempts WHERE ip_hash=? AND minute=?',iph,minute),stmt(env,'DELETE FROM attempts WHERE minute<?',minute-10)]);if(rate[1].results[0].count>10)fail('Troppi tentativi. Riprova tra un minuto.',429);const b=await body(req),raw=String(b.key||'').trim();const k=await stmt(env,'SELECT * FROM licenses WHERE hash=?',await digest(raw)).first();if(!k||!k.enabled||k.expires&&k.expires<=now())fail('Key non valida, sospesa o scaduta.',403);if(k.ip_mode!=='any'&&k.allowed_ip&&k.allowed_ip!==ip)fail('Questa key è riservata a un altro IP.',403);
 const c=cookies(req),proof=/^[a-f0-9]{64}$/.test(c['__Host-ar-device']||'')?c['__Host-ar-device']:token(),proofHash=await digest(proof),device=crypto.randomUUID(),sid=crypto.randomUUID(),secret=token(),ua=(req.headers.get('user-agent')||'Browser').slice(0,300),t=now();
 // D1 batch is a serial, atomic transaction. Limits are checked inside the transaction.
 await env.DB.batch([
 stmt(env,`INSERT INTO devices(id,key_id,proof,label,created) SELECT ?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM devices WHERE key_id=? AND proof=?) AND (SELECT COUNT(*) FROM devices WHERE key_id=? AND enabled=1)<(SELECT max_devices FROM licenses WHERE id=?) AND (SELECT device_mode FROM licenses WHERE id=?)!='fixed' AND NOT EXISTS(SELECT 1 FROM licenses WHERE id=? AND device_mode='first' AND allowed_device IS NOT NULL) AND EXISTS(SELECT 1 FROM licenses l WHERE l.id=? AND l.enabled=1 AND (l.expires IS NULL OR l.expires>?) AND (l.ip_mode='any' OR l.allowed_ip IS NULL OR l.allowed_ip=?) AND (SELECT COUNT(*) FROM sessions WHERE key_id=l.id AND revoked=0 AND expires>?)<l.max_sessions)`,device,k.id,proofHash,ua,t,k.id,proofHash,k.id,k.id,k.id,k.id,k.id,t,ip,t),
 stmt(env,`UPDATE licenses SET allowed_ip=? WHERE id=? AND ip_mode='first' AND allowed_ip IS NULL AND EXISTS(SELECT 1 FROM devices WHERE key_id=? AND proof=? AND enabled=1)`,ip,k.id,k.id,proofHash),
 stmt(env,`UPDATE licenses SET allowed_device=(SELECT id FROM devices WHERE key_id=? AND proof=? AND enabled=1) WHERE id=? AND device_mode='first' AND allowed_device IS NULL`,k.id,proofHash,k.id),
 stmt(env,`UPDATE sessions SET revoked=1 WHERE key_id=? AND device_id=(SELECT id FROM devices WHERE key_id=? AND proof=?)`,k.id,k.id,proofHash),
 stmt(env,`INSERT INTO sessions(id,hash,key_id,device_id,ip,ua,created,seen,expires) SELECT ?,?,?,d.id,?,?,?,?,? FROM devices d JOIN licenses l ON l.id=d.key_id WHERE l.id=? AND d.proof=? AND d.enabled=1 AND l.enabled=1 AND (l.expires IS NULL OR l.expires>?) AND (l.ip_mode='any' OR l.allowed_ip=?) AND (l.device_mode='any' OR l.allowed_device=d.id) AND (SELECT COUNT(*) FROM sessions WHERE key_id=l.id AND revoked=0 AND expires>?)<l.max_sessions`,sid,await digest(secret),k.id,ip,ua,t,t,t+REMEMBER_SECONDS,k.id,proofHash,t,ip,t),
 stmt(env,`INSERT INTO ip_history SELECT id,ip,created,seen FROM sessions WHERE id=?`,sid)
 ]);
 const added=await stmt(env,'SELECT id FROM sessions WHERE id=?',sid).first();if(!added)fail('Accesso negato: limite di dispositivi/sessioni o dispositivo non autorizzato. Chiedi al proprietario di controllare la key.',403);
 const r=json({ok:true});r.headers.append('Set-Cookie',cookie('__Host-ar-session',secret,REMEMBER_SECONDS));r.headers.append('Set-Cookie',cookie('__Host-ar-device',proof,365*86400));return r;
}
const ADMIN_TABLE="CREATE TABLE IF NOT EXISTS admin_sessions(hash TEXT PRIMARY KEY, actor TEXT NOT NULL, credential TEXT NOT NULL, created INTEGER NOT NULL, expires INTEGER NOT NULL, revoked INTEGER NOT NULL DEFAULT 0)";
const same=(a,b)=>{if(a.length!==b.length)return false;let difference=0;for(let i=0;i<a.length;i++)difference|=a.charCodeAt(i)^b.charCodeAt(i);return difference===0};
function adminConfigured(env){if(!env.ADMIN_EMAIL||typeof env.ADMIN_PASSWORD!=='string'||env.ADMIN_PASSWORD.length<20||env.ADMIN_PASSWORD.length>128)fail('Login amministratore non configurato. Esegui ATTIVA-LOGIN.cmd sul tuo PC.',503);}
export async function adminIdentity(req,env){adminConfigured(env);const raw=cookies(req)['__Host-ar-admin'];if(!/^[a-f0-9]{64}$/.test(raw||''))return null;let row;try{row=await stmt(env,'SELECT * FROM admin_sessions WHERE hash=?',await digest(raw)).first()}catch(e){if(String(e.message).includes('no such table'))return null;throw e}if(!row||row.revoked||row.expires<=now()||row.actor!==env.ADMIN_EMAIL.toLowerCase()||!same(row.credential,await digest('admin-v1:'+env.ADMIN_PASSWORD)))return null;return row.actor;}
export async function adminLogin(req,env){origin(req);adminConfigured(env);const t=now(),minute=Math.floor(t/60),iph=await digest('admin:'+ipOf(req));const rate=await env.DB.batch([stmt(env,'INSERT INTO attempts VALUES(?,?,1) ON CONFLICT(ip_hash,minute) DO UPDATE SET count=count+1',iph,minute),stmt(env,'SELECT count FROM attempts WHERE ip_hash=? AND minute=?',iph,minute),stmt(env,'DELETE FROM attempts WHERE minute<?',minute-10)]);if(rate[1].results[0].count>10)fail('Troppi tentativi. Riprova tra un minuto.',429);const b=await body(req),password=String(b.password||'');if(password.length>128)fail('Email o password non corrette.',403);const actual=await digest(password),expected=await digest(env.ADMIN_PASSWORD);if(!same(actual,expected)||String(b.email||'').trim().toLowerCase()!==env.ADMIN_EMAIL.toLowerCase())fail('Email o password non corrette.',403);await stmt(env,ADMIN_TABLE).run();const secret=token(),actor=env.ADMIN_EMAIL.toLowerCase();await env.DB.batch([stmt(env,'DELETE FROM admin_sessions WHERE expires<? OR revoked=1',t),stmt(env,'INSERT INTO admin_sessions VALUES(?,?,?,?,?,0)',await digest(secret),actor,await digest('admin-v1:'+env.ADMIN_PASSWORD),t,t+8*3600)]);await audit(env,actor,'accesso pannello','amministratore');const r=json({ok:true});r.headers.append('Set-Cookie',cookie('__Host-ar-admin',secret,8*3600));return r;}
export const ADMIN_LOGIN_HTML=`<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Accedi al pannello · Armonizza</title><style>body{font:17px system-ui;background:#f7f7f7;color:#161616;display:grid;place-items:center;min-height:95vh;margin:0}main{background:white;padding:32px;border-radius:16px;width:min(370px,80vw)}label{display:block;margin:15px 0}input,button{box-sizing:border-box;width:100%;font:inherit;padding:12px;border:1px solid #aaa;border-radius:8px}button{background:#cbe9fa;cursor:pointer}p{line-height:1.5}</style><main><h1>Pannello privato</h1><p>Accedi per gestire le key.</p><form><label>Email<input type="email" id="email" autocomplete="username" required></label><label>Password<input type="password" id="password" autocomplete="current-password" required maxlength="128"></label><button>Accedi</button></form><p id="message" role="status"></p></main><script>document.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=document.querySelector('button');button.disabled=true;try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:document.querySelector('#email').value,password:document.querySelector('#password').value})});const d=await r.json();if(!r.ok)throw Error(d.error);location.replace('/')}catch(e){document.querySelector('#message').textContent=e.message}finally{button.disabled=false}};</script></html>`;
async function audit(env,actor,action,target){await stmt(env,'INSERT INTO audit VALUES(?,?,?,?,?)',crypto.randomUUID(),actor,action,target,now()).run();}
export async function adminAPI(req,env,actor){const path=new URL(req.url).pathname;if(req.method==='GET'&&path==='/api/admin/keys'){const licenses=(await stmt(env,'SELECT id,label,enabled,expires,max_devices,max_sessions,ip_mode,allowed_ip,device_mode,allowed_device,created FROM licenses ORDER BY created DESC').all()).results;const devices=(await stmt(env,'SELECT id,key_id,label,enabled,created FROM devices ORDER BY created DESC').all()).results;const sessions=(await stmt(env,'SELECT id,key_id,device_id,ip,ua,created,seen,expires,revoked FROM sessions ORDER BY seen DESC LIMIT 2000').all()).results;const ips=(await stmt(env,'SELECT * FROM ip_history ORDER BY last_seen DESC LIMIT 4000').all()).results;return json({licenses,devices,sessions,ips,actor,server_time:now()});}
 if(req.method==='GET'&&path==='/api/admin/audit')return json((await stmt(env,'SELECT * FROM audit ORDER BY created DESC LIMIT 200').all()).results);
 if(req.method!=='POST')fail('Operazione non disponibile.',404);origin(req);const b=await body(req);
 if(path==='/api/admin/keys'){const o=options(b);if(o.device_mode==='fixed')fail('Crea la key con primo dispositivo, poi scegli un dispositivo registrato.');const id=crypto.randomUUID(),key='AR-'+token();await stmt(env,'INSERT INTO licenses VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',id,await digest(key),...Object.values(o),now()).run();await audit(env,actor,'crea key',id);return json({id,key},201);}
 const m=path.match(/^\/api\/admin\/keys\/([a-f0-9-]{36})\/(update|revoke-all|keep-session|keep-device|revoke-session|revoke-device|approve-device|delete)$/);if(!m)fail('Operazione non disponibile.',404);const [,id,action]=m;if(!await stmt(env,'SELECT id FROM licenses WHERE id=?',id).first())fail('Key inesistente.',404);
 if(action==='update'){const o=options(b),previous=await stmt(env,'SELECT * FROM licenses WHERE id=?',id).first();if(o.ip_mode==='first'&&previous.ip_mode==='first')o.allowed_ip=previous.allowed_ip;if(o.device_mode==='first'&&previous.device_mode==='first')o.allowed_device=previous.allowed_device;if(o.allowed_device&&!await stmt(env,'SELECT id FROM devices WHERE id=? AND key_id=? AND enabled=1',o.allowed_device,id).first())fail('Dispositivo non autorizzabile.');await stmt(env,'UPDATE licenses SET label=?,enabled=?,expires=?,max_devices=?,max_sessions=?,ip_mode=?,allowed_ip=?,device_mode=?,allowed_device=? WHERE id=?',...Object.values(o),id).run();}
 if(action==='delete'){if(b.confirm!==true)fail('Conferma l’eliminazione definitiva della key.');await env.DB.batch([stmt(env,'DELETE FROM ip_history WHERE session_id IN (SELECT id FROM sessions WHERE key_id=?)',id),stmt(env,'DELETE FROM omr_jobs WHERE key_id=?',id),stmt(env,'DELETE FROM sessions WHERE key_id=?',id),stmt(env,'DELETE FROM devices WHERE key_id=?',id),stmt(env,'DELETE FROM licenses WHERE id=?',id)]);}
 if(action==='revoke-all')await stmt(env,'UPDATE sessions SET revoked=1 WHERE key_id=?',id).run();
 if(['keep-session','revoke-session'].includes(action)){if(!await stmt(env,'SELECT id FROM sessions WHERE id=? AND key_id=?',b.session,id).first())fail('Sessione inesistente.');await stmt(env,`UPDATE sessions SET revoked=1 WHERE key_id=? AND id${action==='keep-session'?'!=':'='}?`,id,b.session).run();}
 if(action==='approve-device'){const d=await stmt(env,'SELECT enabled FROM devices WHERE id=? AND key_id=?',b.device,id).first();if(!d)fail('Dispositivo inesistente.');const count=await stmt(env,'SELECT COUNT(*) AS n FROM devices WHERE key_id=? AND enabled=1',id).first(),license=await stmt(env,'SELECT max_devices FROM licenses WHERE id=?',id).first();if(!d.enabled&&count.n>=license.max_devices)fail('Limite dispositivi raggiunto. Revoca prima un altro dispositivo.');await stmt(env,`UPDATE devices SET enabled=1 WHERE id=? AND key_id=? AND (enabled=1 OR (SELECT COUNT(*) FROM devices WHERE key_id=? AND enabled=1)<(SELECT max_devices FROM licenses WHERE id=?))`,b.device,id,id,id).run();if(!(await stmt(env,'SELECT enabled FROM devices WHERE id=?',b.device).first()).enabled)fail('Limite dispositivi raggiunto.');}
 if(['keep-device','revoke-device'].includes(action)){if(!await stmt(env,'SELECT id FROM devices WHERE id=? AND key_id=?',b.device,id).first())fail('Dispositivo inesistente.');const op=action==='keep-device'?'!=':'=';await env.DB.batch([stmt(env,`UPDATE devices SET enabled=0 WHERE key_id=? AND id${op}?`,id,b.device),stmt(env,`UPDATE sessions SET revoked=1 WHERE key_id=? AND device_id${op}?`,id,b.device)]);}
 await audit(env,actor,action,id);return json({ok:true});}
async function omr(req,env,s){if(!env.OMR_URL)fail('Riconoscimento PDF/immagini non collegato. MuseScore e MusicXML funzionano già. Per le scansioni configura OMR_URL e OMR_TOKEN sul server.',503);const url=new URL(env.OMR_URL);if(url.protocol!=='https:')fail('Configurazione OMR non valida.',503);const q=new URL(req.url).searchParams,job=q.get('job');if(job&&!await stmt(env,'SELECT id FROM omr_jobs WHERE id=? AND key_id=?',job,s.key_id).first())fail('Importazione non autorizzata.',403);for(const [k,v]of q)if(['job','result','health'].includes(k))url.searchParams.set(k,v);const headers=new Headers();if(env.OMR_TOKEN)headers.set('Authorization','Bearer '+env.OMR_TOKEN);for(const h of ['content-type','x-file-name'])if(req.headers.has(h))headers.set(h,req.headers.get(h));let data;if(req.method==='POST'){if(Number(req.headers.get('content-length'))>4_000_000)fail('File massimo 4 MB.',413);data=await bounded(req,4_000_000);}else if(!['GET','DELETE'].includes(req.method))fail('Metodo non valido.',405);const r=await fetch(url,{method:req.method,headers,body:data,redirect:'error'});if(req.method==='POST'&&r.ok){const result=await r.clone().json();if(!/^[a-f0-9]{32}$/.test(result.id||''))fail('Risposta OMR non valida.',502);await stmt(env,'INSERT INTO omr_jobs VALUES(?,?,?)',result.id,s.key_id,now()).run();}return new Response(r.body,{status:r.status,headers:{'Content-Type':r.headers.get('content-type')||'application/json'}});}
export const LOGIN_HTML=`<!doctype html><html lang="it"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Accedi · Armonizza</title><style>:root{color-scheme:only light}*{box-sizing:border-box}body{font:18px system-ui;background:#fff;color:#000;display:grid;place-items:center;min-height:100vh;margin:0;padding:24px}main{background:#fff;color:#000;padding:36px;border:1px solid #000;border-radius:16px;width:min(100%,440px)}h1{margin-top:0}p{line-height:1.5}label{display:block;margin-top:24px}input,button{width:100%;font:inherit;padding:14px;margin:10px 0;border:1px solid #000;border-radius:8px}input{background:#fff;color:#000;caret-color:#000}input::placeholder{color:#000;opacity:1}input:focus-visible,button:focus-visible{outline:2px solid #000;outline-offset:3px}input:-webkit-autofill{-webkit-box-shadow:0 0 0 1000px #fff inset;-webkit-text-fill-color:#000}button{background:#000;color:#fff;cursor:pointer}button:disabled{background:#000;color:#fff;opacity:1;cursor:wait}::selection{background:#000;color:#fff}.small{font-size:14px}#message{min-height:24px;margin-bottom:0}</style><main><h1>Armonizza basso</h1><p>Inserisci la tua key per accedere.</p><form id="login"><label for="key">Key di accesso</label><input id="key" aria-label="Key di accesso" autocomplete="off" autocapitalize="off" spellcheck="false" required><button>Accedi</button></form><p class="small">L’accesso viene ricordato su questo browser. La key resta soggetta ai limiti e alle autorizzazioni del proprietario.</p><p id="message" role="status"></p></main><script>document.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=document.querySelector('button');button.disabled=true;try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:document.querySelector('input').value})});const d=await r.json();if(!r.ok)throw Error(d.error);location.replace('/')}catch(e){document.querySelector('#message').textContent=e.message}finally{button.disabled=false}};</script></html>`;
function protect(r){const h=new Headers(r.headers);h.set('Cache-Control','private, no-store');h.set('X-Content-Type-Options','nosniff');h.set('Referrer-Policy','same-origin');h.set('X-Frame-Options','DENY');h.set('Content-Security-Policy',"frame-ancestors 'none'; object-src 'none'; base-uri 'self'");return new Response(r.body,{status:r.status,headers:h});}
function remembered(req,r,s){if(s?.refreshCookies){const c=cookies(req);r.headers.append('Set-Cookie',cookie('__Host-ar-session',c['__Host-ar-session'],REMEMBER_SECONDS));r.headers.append('Set-Cookie',cookie('__Host-ar-device',c['__Host-ar-device'],REMEMBER_SECONDS));}return protect(r);}
export default {async fetch(req,env){try{if(!env.DB)fail('Database non configurato.',503);const url=new URL(req.url);if(env.APP_MODE==='admin'){if(url.pathname==='/login'&&req.method==='GET')return protect(new Response(ADMIN_LOGIN_HTML,{headers:{'Content-Type':'text/html; charset=utf-8'}}));if(url.pathname==='/api/admin/login'&&req.method==='POST')return protect(await adminLogin(req,env));const actor=await adminIdentity(req,env);if(!actor)return protect(url.pathname.startsWith('/api/')?json({error:'Accedi al pannello con email e password.'},401):new Response(null,{status:302,headers:{Location:'/login'}}));if(url.pathname==='/api/admin/logout'&&req.method==='POST'){origin(req);await stmt(env,'UPDATE admin_sessions SET revoked=1 WHERE hash=?',await digest(cookies(req)['__Host-ar-admin'])).run();const r=json({ok:true});r.headers.append('Set-Cookie',cookie('__Host-ar-admin','',0));return protect(r);}if(url.pathname==='/api/admin/session'&&req.method==='GET')return protect(json({ok:true,actor}));if(url.pathname.startsWith('/api/'))return protect(await adminAPI(req,env,actor));return protect(await env.ASSETS.fetch(req));}if(env.APP_MODE!=='music')fail('APP_MODE non configurato.',503);if(url.pathname==='/login'&&req.method==='GET'){const current=await validateSession(req,env);if(current)return remembered(req,new Response(null,{status:302,headers:{Location:'/'}}),current);return protect(new Response(LOGIN_HTML,{headers:{'Content-Type':'text/html; charset=utf-8'}}));}if(url.pathname==='/api/auth/login'&&req.method==='POST')return protect(await login(req,env));const session=await validateSession(req,env);if(!session){if(url.pathname.startsWith('/api/'))return protect(json({error:'Accesso scaduto o revocato. Inserisci la key.'},401));return protect(new Response(null,{status:302,headers:{Location:'/login'}}));}if(url.pathname==='/api/auth/session')return remembered(req,json({ok:true,key:session.key_id,device:session.device_id,expires:session.expires}),session);if(url.pathname==='/api/auth/logout'&&req.method==='POST'){origin(req);await stmt(env,'UPDATE sessions SET revoked=1 WHERE id=?',session.id).run();const r=json({ok:true});r.headers.append('Set-Cookie',cookie('__Host-ar-session','',0));return protect(r);}if(url.pathname==='/api/omr'){if(req.method!=='GET')origin(req);return remembered(req,await omr(req,env,session),session);}if(url.pathname.startsWith('/api/'))return protect(json({error:'Non trovato.'},404));return remembered(req,await env.ASSETS.fetch(req),session);}catch(e){return protect(json({error:e.status?e.message:'Errore del server. Verifica configurazione e database.'},e.status||500));}}};
