import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {parseHTML} from 'linkedom';import vm from 'node:vm';import {createRequire} from 'node:module';import {PALETTES} from '../sito/public/editor/palettes.mjs';
const source=new URL('../sito/public/',import.meta.url),{window,document}=parseHTML(fs.readFileSync(new URL('index.html',source),'utf8'));
const values=new Map();Object.assign(globalThis,{window,document,localStorage:{getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},location:{hostname:'localhost',href:'http://localhost',replace(v){this.href=v}},matchMedia:()=>({matches:false}),prompt:()=> 'Testo di prova',confirm:()=>true});
globalThis.Option=class{constructor(text,value){const e=document.createElement('option');e.textContent=text;e.setAttribute('value',value);return e}};
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{configurable:true,get(){return this.__value??this.querySelector('option')?.getAttribute('value')??this.querySelector('option')?.textContent??''},set(v){this.__value=String(v)}});
Object.defineProperty(window.HTMLSelectElement.prototype,'options',{configurable:true,get(){return [...this.children]}});
for(const dialog of document.querySelectorAll('dialog')){dialog.showModal=()=>dialog.setAttribute('open','');dialog.close=()=>dialog.removeAttribute('open')}
globalThis.window={addEventListener(){},print(){}};globalThis.fetch=async url=>{if(String(url).includes('glyphnames'))return {json:async()=>JSON.parse(fs.readFileSync(new URL('editor/fonts/glyphnames.json',source)))};throw Error('Rete inattesa '+url)};
const engine=new URL('editor/vendor/verovio-toolkit-wasm.js',source),mod={exports:{}};vm.runInThisContext('(function(module,exports,require,__dirname,__filename){'+fs.readFileSync(engine,'utf8')+'\n})',{filename:engine.pathname})(mod,mod.exports,createRequire(engine),new URL('.',engine).pathname,engine.pathname);globalThis.verovio=mod.exports;
await new Promise(resolve=>verovio.module.onRuntimeInitialized=resolve);
await import('../sito/public/editor/editor.mjs');
const wait=async()=>{for(let i=0;i<100;i++){if(values.has('ar-score-archive-v1'))return;await new Promise(r=>setTimeout(r,25))}throw Error(document.getElementById('messageBody').textContent||'Avvio non completato')};await wait();
const el=id=>document.getElementById(id),score=()=>JSON.parse(values.get('ar-score-archive-v1'))[0],press=async key=>{const event=new window.Event('keydown',{bubbles:true,cancelable:true});event.key=key;document.body.dispatchEvent(event);await Promise.resolve();};
test('Avvio DOM: carica davvero il motore, incide pagine, tutte le palette e salva la partitura',()=>{assert.ok(el('pages').querySelector('svg'));assert.equal(document.querySelectorAll('.paletteSection').length,18);assert.equal(document.querySelectorAll('.paletteCell').length,PALETTES.reduce((n,p)=>n+p.entries.length,0));assert.equal(score().events.length,0);assert.ok(!el('messageDialog').hasAttribute('open'))});
test('Comandi editor nel DOM: scrive quattro note, inserisce abbellimento, annulla/ripristina e trasferisce basso',async()=>{el('noteInput').onclick();for(const key of ['c','d','e','f'])await press(key);assert.equal(score().events.length,4,el('messageBody').textContent);assert.deepEqual(score().events.map(e=>e.start),[0,16,32,48]);const grace=document.querySelector('[data-item="grace-0"]');await grace.onclick();assert.equal(score().annotations[0].kind,'grace');assert.ok(el('pages').querySelector('.graceGrp'));await document.querySelector('[data-action="undo"]').onclick();assert.equal(score().annotations.length,0);await document.querySelector('[data-action="redo"]').onclick();assert.equal(score().annotations.length,1);await el('toHarmony').onclick();const bass=JSON.parse(values.get('armonizza-v2'));assert.equal(bass.events.length,4);assert.equal(bass.deferHarmony,true);assert.equal(location.href,'harmony.html')});
test('Archivio nel DOM: apre Home e riapre la stessa partitura senza perdere note',async()=>{await el('homeTab').onclick();assert.equal(el('homeScreen').hidden,false);assert.equal(el('workspace').hidden,true);assert.equal(document.querySelectorAll('.archiveCard').length,1);await document.querySelector('.archiveActions button').onclick();assert.equal(el('homeScreen').hidden,true);assert.equal(score().events.length,4)});

test('Proprietà DOM: inserisce e modifica cornice, distanza e ripristina senza perdere le note',async()=>{await document.querySelector('[data-item="layout-5"]').onclick();assert.equal(score().measures[0].spacers.length,1);const input=[...el('propertyFields').querySelectorAll('input')].find(i=>i.parentElement.textContent.includes('Spazio minimo'));const previousPages=el('pages').innerHTML;input.value='30';await input.onchange();assert.notEqual(el('pages').innerHTML,previousPages,'La modifica della distanza deve invalidare la cache SVG');assert.equal(score().measures[0].spacers[0].gapMm,30);await document.querySelector('[data-item="layout-9"]').onclick();assert.ok(el('pages').querySelector('.editorFrame'));assert.equal(score().measures[0].frames[0].text,'Testo di prova');let area=el('propertyFields').querySelector('textarea');area.value='Prima riga\nSeconda riga';await area.onchange();assert.equal(el('pages').querySelectorAll('.editorFrame tspan').length,2);const notes=score().events.length;await document.querySelector('[data-action="undo"]').onclick();assert.equal(el('pages').querySelectorAll('.editorFrame tspan').length,1);await document.querySelector('[data-action="redo"]').onclick();assert.equal(el('pages').querySelectorAll('.editorFrame tspan').length,2);assert.equal(score().events.length,notes);});

test('Icone: ogni cella carica la foto originale e la barra coincide con l’armonizzatore',()=>{for(const cell of document.querySelectorAll('.paletteCell')){const img=cell.querySelector('img');assert.ok(img);assert.ok(fs.existsSync(new URL(img.src)));assert.ok(!img.src.includes('/editor/editor/'));assert.equal(img.getAttribute('alt'),'')}const expected=['breve','whole','half','quarter','eighth','16th','32nd','64th'];assert.deepEqual([...el('durations').children].map(b=>b.dataset.duration),expected);assert.deepEqual([...el('restTools').children].map(b=>b.dataset.duration),expected);assert.deepEqual([...el('durations').querySelectorAll('.toolGlyph')].map(g=>g.textContent),['𝅜','𝅝','𝅗𝅥','𝅘𝅥','𝅘𝅥𝅮','𝅘𝅥𝅯','𝅘𝅥𝅰','𝅘𝅥𝅱']);assert.deepEqual([...el('restTools').querySelectorAll('.toolGlyph')].map(g=>g.textContent),['𝄺','𝄻','𝄼','𝄽','𝄾','𝄿','𝅀','𝅁']);assert.ok(fs.existsSync(new URL('fonts/NotoMusic-Regular.ttf',source)))});
test('Clic sui riquadri trasparenti: seleziona davvero le note e completa un glissando',async()=>{if(el('noteInput').getAttribute('aria-pressed')==='true')el('noteInput').onclick();const first=score().events[0],last=score().events[3];const click=async id=>{const target=document.getElementById('bbox-'+id)?.querySelector('rect')||document.getElementById(id);assert.ok(target);target.dispatchEvent(new window.Event('click',{bubbles:true}));await Promise.resolve()};await click(first.id);assert.ok(document.getElementById(first.id).classList.contains('selected'));const item=[...document.querySelectorAll('.paletteCell')].find(b=>b.title.includes('Glissando'));assert.ok(item);await item.onclick();await click(last.id);const ann=score().annotations.find(a=>a.kind==='glissando');assert.equal(ann.event,first.id);assert.equal(ann.end,last.id);const group=document.getElementById(ann.id);assert.ok(group);const target=group.querySelector('path')||group;target.dispatchEvent(new window.Event('click',{bubbles:true}));await Promise.resolve();await document.querySelector('[data-action="delete"]').onclick();assert.ok(!score().annotations.some(a=>a.id===ann.id));assert.equal(score().events.length,4)});
test('Barra delle pause: sceglie durata e inserisce una pausa con la tastiera',async()=>{document.getElementById(score().events.at(-1).id).dispatchEvent(new window.Event('click',{bubbles:true}));await Promise.resolve();await el('restTools').querySelector('[data-duration="eighth"]').onclick();assert.equal(el('restsMenu').open,false);assert.equal(el('restTools').querySelector('[data-duration="eighth"]').getAttribute('aria-pressed'),'true');await press('c');const event=score().events.at(-1);assert.equal(event.kind,'rest');assert.equal(event.duration,'eighth');await document.querySelector('[data-action="undo"]').onclick();assert.equal(score().events.length,4)});

test('Mouse sul pentagramma: crea una nota valida una sola volta, anche nel SVG annidato',async()=>{await el('durations').querySelector('[data-duration="quarter"]').onclick();const measure=document.getElementById(score().measures[1].id),staff=measure.querySelector('g.staff:not(.bounding-box)'),paths=[...staff.children].filter(n=>n.localName==='path');assert.equal(paths.length,5);staff.getScreenCTM=()=>({a:.04,b:0,c:0,d:.04,e:100,f:200});const coords=paths[0].getAttribute('d').match(/-?[\d.]+/g).map(Number);const event=new window.Event('click',{bubbles:true});event.clientX=100+(coords[0]+300)*.04;event.clientY=200+coords[1]*.04;const before=score().events.length;paths[0].dispatchEvent(event);await Promise.resolve();assert.equal(score().events.length,before+1,el('messageBody').textContent);const note=score().events.find(e=>e.staff===0&&e.start===64);assert.ok(note,JSON.stringify(score().events));assert.equal(note.pitches[0],77);assert.ok(!el('messageDialog').hasAttribute('open'));});

test('Layout dei SVG: solo la pagina esterna riceve altezza automatica',()=>{const css=fs.readFileSync(new URL('editor/editor.css',source),'utf8');assert.ok(css.includes('.editorPage>svg{display:block;width:100%;height:auto}'));assert.ok(!css.includes('.editorPage svg{display:block;width:100%;height:auto}'))});

test('Mouse: sostituisce nota-pausa-nota sul quarto esatto senza spostarla',async()=>{const original=score().events.find(e=>e.staff===0&&e.start===64);assert.ok(original);for(const kind of ['rest','note','rest','note']){const target=el(kind==='rest'?'restTools':'durations').querySelector('[data-duration="quarter"]');await target.onclick();const group=document.getElementById(score().events.find(e=>e.staff===0&&e.start===64).id),staff=group.closest('g.staff:not(.bounding-box)');staff.getScreenCTM=()=>({a:.04,b:0,c:0,d:.04,e:100,f:200});const coords=[...staff.children].find(n=>n.localName==='path').getAttribute('d').match(/-?[\d.]+/g).map(Number);const event=new window.Event('click',{bubbles:true});event.clientX=100+(coords[0]+300)*.04;event.clientY=200+coords[1]*.04;group.dispatchEvent(event);await Promise.resolve();assert.equal(score().events.find(e=>e.staff===0&&e.start===64).kind,kind,el('messageBody').textContent);assert.equal(score().events.filter(e=>e.staff===0&&e.start===64).length,1);}assert.ok(!el('messageDialog').hasAttribute('open'))});
test('Trasferimento DOM: voce senza basso apre armonizzatore vuoto e conserva una copia precedente',async()=>{values.set('armonizza-v2',JSON.stringify({events:[{midi:48}],key:'Do maggiore'}));el('staffChoice').value='1';el('voice').value='4';await el('toHarmony').onclick();assert.deepEqual(JSON.parse(values.get('armonizza-v2')).events,[]);assert.equal(JSON.parse(values.get('ar-harmony-backup-before-editor')).events[0].midi,48);assert.equal(location.href,'harmony.html')});
test('Esportazione DOM: scelta MusicXML, MIDI e PDF scaricabile separata dalla stampa',async()=>{await document.querySelector('[data-action="exportMenu"]').onclick();assert.ok(el('editorExportDialog').hasAttribute('open'));for(const action of ['exportXml','exportMidi','exportPdf','exportJson'])assert.ok(el('editorExportDialog').querySelector(`[data-action="${action}"]`));assert.equal(el('pdfStaffSize').options.length,5);el('closeExport').onclick();assert.ok(!el('editorExportDialog').hasAttribute('open'))});
