import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';
import {engravedPages,frameHeight} from '../sito/public/editor/frame-render.mjs';
import {systemPlan} from '../sito/public/editor/layout.mjs';
import {createRequire} from 'node:module';
import {newScore,ScoreSession,ScoreArchive,validate,length,measureStart,effectiveMeter,bassForHarmony} from '../sito/public/editor/model.mjs';
import {scoreMei,scoreMusicXml,performance} from '../sito/public/editor/encoding.mjs';
import {ITEMS,PALETTES} from '../sito/public/editor/palettes.mjs';
const glyphs=JSON.parse(fs.readFileSync(new URL('../sito/public/editor/fonts/glyphnames.json',import.meta.url)));
const seed=(opts={})=>{const s=new ScoreSession(newScore(opts));s.insert({start:0,midi:48});const first=s.selection;s.insert({start:16,midi:50});const end=s.selection;s.selection=first;return {s,first,end}};
const pendingLayout=new Set(['fixed','hframe','measureframe','properties']);
let toolkit;
const ready=new Promise((resolve,reject)=>{const file=new URL('../sito/public/editor/vendor/verovio-toolkit-wasm.js',import.meta.url),module={exports:{}};try{vm.runInThisContext('(function(module,exports,require,__dirname,__filename){'+fs.readFileSync(file,'utf8')+'\n})',{filename:file.pathname})(module,module.exports,createRequire(file),new URL('.',file).pathname,file.pathname);const v=module.exports;v.module.onRuntimeInitialized=()=>{toolkit=new v.toolkit();toolkit.setOptions({font:'Leland',svgBoundingBoxes:true,breaks:'auto',header:'none',footer:'none'});resolve()}}catch(e){reject(e)}});
test('Editor: 18 categorie, identificatori unici e glifi presenti nel dizionario musicale',()=>{assert.equal(PALETTES.length,18);assert.equal(new Set(ITEMS.map(i=>i.id)).size,ITEMS.length);for(const i of ITEMS)if(i.glyph)assert.ok(glyphs[i.glyph],i.glyph)});
for(const item of ITEMS)test('Tavolozza: '+item.name+' ['+item.id+']',async()=>{await ready;const {s,first,end}=seed();if(item.kind==='layout'&&item.value==='down')s.score.events[0].staff=0;if(item.kind==='layout'&&pendingLayout.has(item.value)){assert.throws(()=>s.apply(item,end),/completato/);return}if(item.kind==='meter'){s.score.events[0].duration='eighth';s.score.events[1].duration='eighth';s.score.events[1].start=8;}if(item.kind==='arpeggio')s.insert({start:0,chord:true,midi:55});s.selection=first;s.apply(item,end,'Testo di prova');validate(s.score);const mei=scoreMei(s.score,glyphs);assert.ok(toolkit.loadData(mei));const svg=toolkit.renderToSVG(1);assert.match(svg,/<svg/);assert.ok(svg.includes(first));assert.match(scoreMusicXml(s.score,glyphs),/<score-partwise/);if(item.kind==='grace'){const a=s.score.annotations.at(-1);for(let i=0;i<a.pitches.length;i++)assert.ok(svg.includes(a.id+'-g'+i),'Abbellimento assente: '+i)}else if(!['clef','key','meter','layout','barline','accidental','transpose','tremolo'].includes(item.kind)){const ann=s.score.annotations.at(-1);assert.ok(svg.includes(ann.id),'Elemento musicale assente dallo SVG');}assert.ok(s.undo());assert.ok(s.redo());validate(s.score);});
test('Modifiche impossibili: sovrapposizioni non cambiano la partitura',()=>{const {s}=seed(),before=structuredClone(s.score);assert.throws(()=>s.insert({start:8,midi:51}),/sovrapposte/);assert.deepEqual(s.score,before)});
test('Linee: rifiuta estremi precedenti, altra voce, altro pentagramma e glissando da pausa',()=>{const {s,first,end}=seed(),gliss=ITEMS.find(i=>i.kind==='glissando');assert.throws(()=>s.apply(gliss,first),/successiva/);s.insert({start:32,staff:0,midi:60});const other=s.selection;s.selection=first;assert.throws(()=>s.apply(gliss,other),/stessa voce/);s.insert({start:32,voice:2,midi:52});const voice=s.selection;s.selection=first;assert.throws(()=>s.apply(gliss,voice),/stessa voce/);s.insert({start:0,kind:'rest'});assert.throws(()=>s.apply(gliss,end),/non una pausa/)});
test('Tremolo doppio: richiede note uguali nel ritmo, adiacenti e nella stessa battuta',()=>{const {s,first,end}=seed(),item=ITEMS.find(i=>i.kind==='tremolo'&&i.value.pair);s.apply(item,end);assert.match(scoreMei(s.score,glyphs),/<fTrem/);const {s:t}=seed();t.insert({start:32,midi:52});const far=t.selection;t.selection=t.score.events[0].id;assert.throws(()=>t.apply(item,far),/consecutive/)});
for(const d of ['whole','half','quarter','eighth','16th','32nd','64th'])for(const key of ['Do maggiore','Re maggiore','Mi♭ maggiore','La minore'])test('Abbellimenti su tutte le durate: '+d+' '+key,async()=>{if(!newScore({key}).key)return;await ready;const s=new ScoreSession(newScore({key}));s.insert({start:0,midi:60,duration:d});for(const grace of ITEMS.filter(i=>i.kind==='grace')){s.apply(grace);const a=s.score.annotations.at(-1);assert.equal(a.pitches.length,grace.value.count);assert.ok(toolkit.loadData(scoreMei(s.score,glyphs)));assert.ok(toolkit.renderToSVG(1).includes(a.id+'-g0'));s.undo()}});
test('Cambio metrica persiste: eventi successivi spostati, battute inserite ed eliminate coerenti',()=>{const s=new ScoreSession(newScore());s.insert({start:64,midi:50});const next=s.selection;s.insert({start:0,midi:48});s.apply({kind:'meter',value:'3/4'});assert.equal(effectiveMeter(s.score,2),'3/4');assert.equal(s.score.events.find(e=>e.id===next).start,48);assert.equal(measureStart(s.score,3),144);s.addMeasure(1);assert.equal(s.score.events.find(e=>e.id===next).start,96);s.removeMeasure(1);assert.equal(s.score.events.find(e=>e.id===next).start,48)});
test('Trasferimento basso conserva ritmi, pause, accordi, tonalità e modulazioni',()=>{const s=new ScoreSession(newScore({key:'Re maggiore'}));s.insert({start:0,midi:50,dotted:true});s.insert({start:24,kind:'rest',duration:'eighth'});s.insert({start:32,midi:54,duration:'half'});s.insert({start:32,midi:66,duration:'half',chord:true});s.insert({start:64,midi:55});s.apply({kind:'key',value:1});const data=bassForHarmony(s.score);assert.equal(data.key,'Re maggiore');assert.deepEqual(data.events.map(e=>[e.kind,e.start,e.midi,e.duration,e.dotted]),[['note',0,50,'quarter',true],['rest',24,undefined,'eighth',false],['note',32,54,'half',false],['note',64,55,'quarter',false]]);assert.equal(data.tonalEvents[0].key,'Sol maggiore');assert.equal(data.measureCount,4);assert.equal(data.deferHarmony,true)});
test('Archivio salva, riapre senza alias, sostituisce, elimina e segnala dati corrotti',()=>{const values=new Map(),storage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v)},a=new ScoreArchive(storage),s=newScore();a.save(s);s.title='Aggiornata';a.save(s);assert.equal(a.list().length,1);const opened=a.open(s.id);opened.title='Altro';assert.equal(a.open(s.id).title,'Aggiornata');a.remove(s.id);assert.equal(a.list().length,0);values.set(a.key,'{err');assert.throws(()=>a.list(),/danneggiato/)});
test('Cancella nota o battuta: elimina tutti gli elementi agganciati e annulla ripristina',()=>{const {s,first,end}=seed();s.apply(ITEMS.find(i=>i.kind==='glissando'),end);s.selection=end;s.remove();assert.equal(s.score.annotations.length,0);s.undo();assert.equal(s.score.annotations.length,1);s.removeMeasure(0);assert.equal(s.score.events.length,0);assert.equal(s.score.annotations.length,0);s.undo();assert.equal(s.score.events.length,2)});
test('Ascolto: dinamica, tempo, pedale, legature e ripetizioni modificano gli eventi audio',()=>{const {s,first,end}=seed();s.apply({kind:'dynamic',value:'pp'});s.apply({kind:'tempo',value:{bpm:60,unit:2}});let p=performance(s.score);assert.equal(p.notes[0].volume,.35);assert.equal(p.notes[1].seconds,.5);s.apply({kind:'pedal',value:'line'},end);assert.equal(performance(s.score).notes[0].length,32);s.score.annotations=[];s.score.events[1].pitches=[48];s.score.events[0].tieNext=true;p=performance(s.score);assert.equal(p.notes.length,1);assert.equal(p.notes[0].length,32);s.score.measures[0].right='rptend';assert.deepEqual(performance(s.score).itinerary,[0,0,1,2,3])});
test('MusicXML: durate intere anche per terzine, ordine degli accordi e modo minore',()=>{const s=new ScoreSession(newScore({key:'La minore'}));s.insert({start:0,midi:57,duration:'64th',tuplet:true});s.insert({start:0,midi:60,duration:'64th',tuplet:true,chord:true});const xml=scoreMusicXml(s.score);assert.match(xml,/<divisions>768<\/divisions>/);assert.match(xml,/<duration>32<\/duration>/);assert.match(xml,/<mode>minor<\/mode>/);assert.match(xml,/<chord\/><pitch>/);assert.ok(!xml.includes('<duration>0.'))});
test('MusicXML: fine delle linee nella battuta della nota finale',()=>{const s=new ScoreSession(newScore());s.insert({start:0,midi:48});const first=s.selection;s.insert({start:80,midi:52});const last=s.selection;s.selection=first;s.apply({kind:'hairpin',value:'cres'},last);const xml=scoreMusicXml(s.score);const bars=[...xml.matchAll(/<measure [^>]*>([\s\S]*?)<\/measure>/g)].map(x=>x[1]);assert.match(bars[0],/wedge type="crescendo"/);assert.ok(!bars[0].includes('wedge type="stop"'));assert.match(bars[1],/wedge type="stop"/)});
test('Navigazione: editor iniziale, armonizzatore separato, autenticazione conservata e offline pulito',()=>{const root=new URL('../sito/public/',import.meta.url),html=fs.readFileSync(new URL('index.html',root),'utf8'),harmony=fs.readFileSync(new URL('harmony.html',root),'utf8'),js=fs.readFileSync(new URL('editor/editor.mjs',root),'utf8');assert.ok(html.includes('id="toHarmony"'));assert.ok(harmony.includes('id="solve"'));assert.match(harmony,/href="index.html"/);assert.match(js,/bassForHarmony/);assert.match(js,/ar-harmony-backup-before-editor/);assert.match(js,/api\/auth\/session/);assert.ok(!fs.readFileSync(new URL('../offline/index.html',import.meta.url),'utf8').includes('editor-return'));const ids=[...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);const css=fs.readFileSync(new URL('editor/editor.css',root),'utf8');assert.match(css,/@media\(max-width:900px\)/);assert.match(css,/touch-action:pan-x pan-y/);assert.match(css,/mobileClosed\{display:none/)});
test('Interruzioni di pagina: vengono realmente incise in due pagine',async()=>{await ready;const {s}=seed();s.apply({kind:'layout',value:'page'});toolkit.setOptions({breaks:'encoded'});assert.ok(toolkit.loadData(scoreMei(s.score)));assert.equal(toolkit.getPageCount(),2);toolkit.setOptions({breaks:'auto'})});
test('Cambio metrico ricalcola tutte le battute seguenti e si arresta al cambio esplicito successivo',()=>{const s=new ScoreSession(newScore({bars:5}));for(let i=0;i<5;i++)s.insert({start:i*64,midi:48+i});s.selection=s.score.events[0].id;s.apply({kind:'meter',value:'3/4'});assert.deepEqual(s.score.events.map(e=>e.start),[0,48,96,144,192]);s.selection=s.score.events[3].id;s.apply({kind:'meter',value:'4/4'});assert.deepEqual(s.score.events.map(e=>e.start),[0,48,96,144,208]);s.removeMeasure(0);assert.deepEqual(s.score.events.map(e=>e.start),[0,48,96,160]);assert.equal(effectiveMeter(s.score,0),'3/4')});
test('Cambio metrico rifiuta una nota che eccede una battuta successiva senza modificare il progetto',()=>{const s=new ScoreSession(newScore());s.insert({start:0,midi:48});const first=s.selection;s.insert({start:112,midi:50});s.selection=first;const before=structuredClone(s.score);assert.throws(()=>s.apply({kind:'meter',value:'3/4'}),/non entrano/);assert.deepEqual(s.score,before)});
test('Progetti esterni: identifica proprietà, ID duplicati e chiavi non valide senza incidere XML arbitrario',()=>{const s=newScore();s.measures[0].id='x" onload="';assert.throws(()=>validate(s),/Identificatore/);const a=newScore();a.measures[1].id=a.measures[0].id;assert.throws(()=>validate(a),/duplicato/);assert.throws(()=>newScore({key:'__proto__'}),/Tonalità/);const b=newScore();b.staves[0].clef.shape='G"';assert.throws(()=>validate(b),/Chiave/)});
test('Battute vuote: applica chiave, armatura, metrica e stanghetta senza inventare note',()=>{const s=new ScoreSession(newScore());s.apply({kind:'clef',value:{shape:'F',line:4}});s.apply({kind:'key',value:-1});s.apply({kind:'meter',value:'3/4'});s.apply({kind:'barline',value:'end'});assert.equal(s.score.events.length,0);assert.equal(s.score.staves[1].clef.shape,'F');assert.equal(s.score.measures[0].keyFifths,-1);assert.equal(effectiveMeter(s.score,3),'3/4');assert.equal(s.score.measures[0].right,'end');s.insert({start:0,midi:48});assert.equal(bassForHarmony(s.score).meter,'3/4')});

test('Spaziatori: la distanza SVG cresce e torna al valore normale nel sistema successivo',async()=>{
 await ready;const s=new ScoreSession(newScore({bars:8}));s.staffCursor=1;s.score.measures[3].layout=['system'];
 const render=()=>{toolkit.setOptions({unit:9,pageWidth:2100,pageHeight:2970,breaks:'encoded',svgBoundingBoxes:true,svgAdditionalAttribute:['staff@n']});assert.ok(toolkit.loadData(scoreMei(s.score)));const {document}=parseHTML('<html></html>');const holder=document.createElement('div');holder.append(...engravedPages(toolkit,s.score,document,spacing=>scoreMei(s.score,{},spacing)));return holder};
 const distances=doc=>[...doc.querySelectorAll('g.system')].filter(g=>!g.classList.contains('bounding-box')).map(g=>{const ms=[...g.querySelectorAll('g.measure')].find(g=>!g.classList.contains('bounding-box'));const st=[...ms.querySelectorAll('g.staff')].filter(g=>!g.classList.contains('bounding-box'));return st.slice(0,2).map(st=>Number([...st.children].find(c=>c.tagName.toLowerCase()==='path').getAttribute('d').split(/\s/)[1])).reduce((a,b)=>b-a)});
 const before=distances(render());s.apply({kind:'layout',value:'up'});s.edit(()=>s.score.measures[0].spacers[0].gapMm=32);const after=distances(render());assert.ok(after[0]>before[0]+1000,JSON.stringify({before,after}));assert.equal(after[1],before[1]);s.undo();s.undo();assert.deepEqual(distances(render()),before);toolkit.setOptions({breaks:'auto'});
});
test('Spaziatori: limiti, pentagrammi adiacenti, undo e dati musicali intatti',()=>{const s=new ScoreSession(newScore());const before=structuredClone(s.score.events);assert.throws(()=>s.apply({kind:'layout',value:'down'}),/adiacenti/);s.apply({kind:'layout',value:'up'});assert.deepEqual(s.score.events,before);const old=structuredClone(s.score);assert.throws(()=>s.edit(()=>s.score.measures[0].spacers[0].gapMm=-1),/Distanza/);assert.deepEqual(s.score,old);s.addMeasure(0);assert.equal(s.score.measures[1].spacers.length,1);s.removeMeasure(1);assert.equal(s.score.measures.some(m=>m.spacers?.length),false);s.undo();assert.equal(s.score.measures[1].spacers.length,1)});
test('Cornici: native note e spanner conservati, altezza, testo sicuro e paginazione',async()=>{
 await ready;const s=new ScoreSession(newScore({bars:12}));for(let m=0;m<12;m++)s.insert({start:m*64,midi:48+m});s.selection=s.score.events[0].id;s.apply({kind:'layout',value:'textframe'},undefined,'Titolo <script> &\nSeconda riga');s.edit(()=>s.score.measures[0].frames[0].heightMm=100);s.selection=s.score.events[4].id;s.apply({kind:'layout',value:'vframe'});s.edit(()=>s.score.measures[4].frames[0].heightMm=100);
 toolkit.setOptions({unit:9,pageWidth:2100,pageHeight:2970,pageMarginTop:250,pageMarginBottom:180,pageMarginLeft:180,pageMarginRight:180,breaks:'encoded',svgBoundingBoxes:true});assert.ok(toolkit.loadData(scoreMei(s.score)));const {document}=parseHTML('<html></html>');const native=Array.from({length:toolkit.getPageCount()},(_,i)=>toolkit.renderToSVG(i+1)).join(''),pages=engravedPages(toolkit,s.score,document),combined=pages.map(p=>p.outerHTML).join('');assert.ok(pages.length>=2);assert.ok(!combined.includes('<script>'));assert.ok(combined.includes('Titolo &lt;script&gt; &amp;'));assert.equal(pages.flatMap(p=>[...p.querySelectorAll('.editorFrame')]).length,2);
 const original=parseHTML(native).document;for(const event of s.score.events){const old=original.getElementById(event.id),next=pages.map(p=>p.querySelector('[id="'+event.id+'"]')).find(Boolean);assert.ok(next);assert.equal(next.outerHTML,old.outerHTML,'La cornice non deve ridisegnare le note')};toolkit.setOptions({breaks:'auto'});
});
test('Cornici: testo troppo lungo rifiutato senza cambiare partitura, giunzioni coerenti',()=>{const s=new ScoreSession(newScore());const before=structuredClone(s.score);assert.throws(()=>s.apply({kind:'layout',value:'textframe'},undefined,'riga\n'.repeat(400)),/150 mm/);assert.deepEqual(s.score,before);s.apply({kind:'layout',value:'vframe'});assert.equal(frameHeight(s.score.measures[0].frames[0]),15);s.measureCursor=2;s.apply({kind:'layout',value:'textframe'},undefined,'Titolo');assert.deepEqual([...systemPlan(s.score).keys()],[0,2]);s.undo();assert.deepEqual([...systemPlan(s.score).keys()],[0])});

test('Aggiungi battuta: eredita la metrica senza una nuova indicazione di tempo',async()=>{await ready;const s=new ScoreSession(newScore({meter:'3/4'}));s.insert({start:0,midi:48});const before=scoreMei(s.score);s.addMeasure();s.addMeasure();assert.ok(s.score.measures.every(m=>m.meter===undefined));assert.equal((scoreMei(s.score).match(/meter.count=/g)||[]).length,(before.match(/meter.count=/g)||[]).length);assert.equal((scoreMusicXml(s.score).match(/<time>/g)||[]).length,1);s.removeMeasure(1);assert.equal((scoreMusicXml(s.score).match(/<time>/g)||[]).length,1);s.selection=s.score.events[0].id;s.apply({kind:'meter',value:'2/4'});s.addMeasure();assert.equal(effectiveMeter(s.score,s.score.measures.length-1),'2/4');assert.equal(s.score.measures.at(-1).meter,undefined);toolkit.setOptions({breaks:'auto'});assert.ok(toolkit.loadData(scoreMei(s.score)));const {document}=parseHTML(toolkit.renderToSVG(1));assert.equal(document.querySelectorAll('g.meterSig:not(.bounding-box)').length,2,'Una sola metrica per pentagramma')});

test('Inserimento prima di un cambio metrico: sposta le note della durata del tempo precedente',()=>{const s=new ScoreSession(newScore());s.insert({start:0,midi:48});s.apply({kind:'meter',value:'3/4'});s.addMeasure(0);assert.equal(effectiveMeter(s.score,0),'4/4');assert.equal(effectiveMeter(s.score,1),'3/4');assert.equal(s.score.events[0].start,64);assert.equal(s.score.measures[0].meter,undefined)});

test('Partiture già salvate: non ristampa le metriche duplicate dalle vecchie aggiunte di battuta',async()=>{await ready;const s=newScore({bars:8});s.measures[4].meter='4/4';s.measures[5].meter='4/4';assert.equal((scoreMusicXml(s).match(/<time>/g)||[]).length,1);assert.equal((scoreMei(s).match(/meter.count=/g)||[]).length,1);s.measures[6].meter='3/4';assert.equal((scoreMusicXml(s).match(/<time>/g)||[]).length,2);assert.equal((scoreMei(s).match(/meter.count=/g)||[]).length,2);toolkit.setOptions({breaks:'auto'});assert.ok(toolkit.loadData(scoreMei(s)))});

test('Figure oltre battuta: incisione nativa conserva note e tutte le legature',async()=>{await ready;for(const [meter,start,duration,dotted,tuplet] of [['4/4',0,'breve',false,false],['3/4',32,'whole',true,false],['1/64',0,'64th',true,false],['4/4',60,'quarter',false,true]]){const s=new ScoreSession(newScore({meter,bars:1}));s.insert({start,midi:60,duration,dotted,tuplet});toolkit.setOptions({breaks:'auto',svgBoundingBoxes:true});assert.ok(toolkit.loadData(scoreMei(s.score)),meter);const svg=Array.from({length:toolkit.getPageCount()},(_,i)=>toolkit.renderToSVG(i+1)).join('');for(const e of s.score.events)assert.ok(svg.includes(e.id),e.duration);assert.equal((scoreMei(s.score).match(/<tie /g)||[]).length,s.score.events.length-1)}});

test('Incisione reale: quattro voci complete, nessuna pausa aggiunta; pause nascoste non disegnate',async()=>{await ready;const s=new ScoreSession(newScore({bars:1}));for(const staff of [0,1])for(const voice of [1,2,3,4])s.insert({start:0,staff,voice,duration:'whole',midi:48+staff*12+voice});assert.ok(toolkit.loadData(scoreMei(s.score,glyphs)));let svg=toolkit.renderToSVG(1);assert.ok(!/class="(?:rest|mRest)"/.test(svg));s.score.events.find(e=>e.voice===4&&e.staff===1).kind='rest';s.score.events.find(e=>e.voice===4&&e.staff===1).hidden=true;assert.ok(toolkit.loadData(scoreMei(s.score,glyphs)));svg=toolkit.renderToSVG(1);assert.ok(!/class="(?:rest|mRest)"/.test(svg));});
