import test from 'node:test';
import assert from 'node:assert/strict';
import {DOMParser} from 'linkedom';
import {newScore,ScoreSession,measureStart} from '../sito/public/editor/model.mjs';
import {scoreMusicXml} from '../sito/public/editor/encoding.mjs';
import {importXml,importFile} from '../sito/public/editor/import-score.mjs';
import {ITEMS} from '../sito/public/editor/palettes.mjs';
globalThis.DOMParser=DOMParser;
for(const key of ['Do maggiore','Re maggiore','Mi♭ maggiore','La minore'])test('MusicXML andata/ritorno: ritmi, due pentagrammi, voci, accordi e modo '+key,()=>{const s=new ScoreSession(newScore({key}));for(const staff of [0,1]){s.insert({start:0,staff,midi:60-staff*12,dotted:true});s.insert({start:24,staff,kind:'rest',duration:'eighth'});s.insert({start:32,staff,midi:62-staff*12,duration:'half'});s.insert({start:32,staff,midi:66-staff*12,duration:'half',chord:true});s.insert({start:0,staff,voice:2,midi:67-staff*12,duration:'whole'});}const restored=importXml(scoreMusicXml(s.score)).score;assert.equal(restored.key,key);const events=x=>x.events.map(e=>[e.start,e.staff,e.voice,e.kind,e.duration,e.dotted,e.pitches]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]||a[2]-b[2]);assert.deepEqual(events(restored),events(s.score));assert.equal(restored.staves.length,2);assert.equal(restored.measures.length,4)});
test('MusicXML andata/ritorno: terzine',()=>{const s=new ScoreSession(newScore());for(let i=0;i<3;i++)s.insert({start:i*16/3,midi:48+i,duration:'eighth',tuplet:true});const restored=importXml(scoreMusicXml(s.score)).score;assert.deepEqual(restored.events.map(e=>[e.start,e.tuplet,e.duration]),s.score.events.map(e=>[e.start,e.tuplet,e.duration]))});
test('MusicXML andata/ritorno: abbellimenti e linee fra battute',()=>{const s=new ScoreSession(newScore());s.insert({start:0,midi:48});const first=s.selection;s.apply(ITEMS.find(i=>i.kind==='grace'));s.insert({start:80,midi:55});const end=s.selection;s.selection=first;for(const [kind,value]of [['hairpin','cres'],['octave',8],['pedal','line'],['glissando','wavy'],['articulation','slur']])s.apply({kind,value},end);const restored=importXml(scoreMusicXml(s.score)).score;assert.equal(restored.annotations.filter(a=>a.end).length,5);assert.equal(restored.annotations.filter(a=>a.kind==='grace').length,1)});
test('MuseScore: due pentagrammi, pause e abbellimenti con avviso di importazione sperimentale',()=>{const xml='<museScore version="4.0"><Score><Staff id="1"><Measure><voice><TimeSig><sigN>4</sigN><sigD>4</sigD></TimeSig><Chord><durationType>quarter</durationType><Note><pitch>60</pitch></Note></Chord></voice></Measure></Staff><Staff id="2"><Measure><voice><Clef><concertClefType>F</concertClefType></Clef><Chord><acciaccatura/><durationType>eighth</durationType><Note><pitch>50</pitch></Note></Chord><Chord><durationType>quarter</durationType><Note><pitch>48</pitch></Note></Chord><Rest><durationType>quarter</durationType></Rest></voice></Measure></Staff></Score></museScore>';const {score,warnings}=importXml(xml);assert.equal(score.staves.length,2);assert.equal(score.events.length,3);assert.equal(score.annotations[0].kind,'grace');assert.deepEqual(score.annotations[0].pitches,[50]);assert.ok(warnings.length)});
test('Importazione: rifiuta punti multipli e gruppi irregolari non supportati',()=>{assert.throws(()=>importXml('<museScore><Score><Staff><Measure><voice><Chord><durationType>quarter</durationType><dots>2</dots><Note><pitch>48</pitch></Note></Chord></voice></Measure></Staff></Score></museScore>'),/punti multipli/);const s=new ScoreSession(newScore());s.insert({start:0,midi:48,duration:'eighth',tuplet:true});assert.throws(()=>importXml(scoreMusicXml(s.score).replace('<actual-notes>3','<actual-notes>5')),/irregolare/)});
test('Importazione JSON mantiene tutte le proprietà degli elementi',async()=>{const s=new ScoreSession(newScore());s.insert({start:0,midi:48});s.apply(ITEMS.find(i=>i.kind==='grace'));const file={name:'progetto.json',size:200,text:async()=>JSON.stringify(s.score)},restored=await importFile(file);assert.deepEqual(restored.score,s.score);assert.deepEqual(restored.warnings,[])});
for(const item of ITEMS.filter(i=>i.kind==='grace'))test('MusicXML: conserva altezze e posizione delle '+item.name,()=>{const s=new ScoreSession(newScore());s.insert({start:0,midi:48});s.apply(item);s.insert({start:16,midi:50});const restored=importXml(scoreMusicXml(s.score)).score,graces=restored.annotations.filter(a=>a.kind==='grace');assert.deepEqual(graces.flatMap(a=>a.pitches),s.score.annotations[0].pitches);assert.ok(graces.every(a=>a.event===restored.events[0].id));assert.ok(graces.every(a=>a.value.attach===item.value.attach));assert.ok(graces.every(a=>a.value.duration===item.value.duration))});

test('MusicXML: cornici, spaziatori e interruzioni tornano nella stessa battuta',()=>{const s=new ScoreSession(newScore({bars:8}));s.apply({kind:'layout',value:'up'});s.apply({kind:'layout',value:'textframe'},undefined,'Titolo < &\nSeconda riga');s.measureCursor=2;s.apply({kind:'layout',value:'page'});s.measureCursor=4;s.apply({kind:'layout',value:'vframe'});s.edit(()=>s.score.measures[4].frames[0].heightMm=45);const xml=scoreMusicXml(s.score),bars=[...xml.matchAll(/<measure [^>]*>([\s\S]*?)<\/measure>/g)].map(m=>m[1]);assert.ok(!bars[2].includes('new-page'));assert.ok(bars[3].includes('new-page'));const restored=importXml(xml).score,metadata=score=>score.measures.map(m=>({layout:m.layout,spacers:m.spacers?.map(({id,...p})=>p),frames:m.frames?.map(({id,...p})=>p)}));assert.deepEqual(metadata(restored),metadata(s.score));assert.equal(restored.events.length,0);const nativeXml=xml.replace(/<identification>[\s\S]*?<\/identification>/,'');const native=importXml(nativeXml).score;assert.deepEqual(native.measures[2].layout,['page']);assert.ok(Math.abs(native.measures[0].spacers[0].gapMm-18)<1e-7)});
test('MusicXML: metadati di impaginazione falsi o incoerenti vengono rifiutati',()=>{const s=newScore();const xml=scoreMusicXml(s);assert.throws(()=>importXml(xml.replace(/<miscellaneous-field[^>]*>[\s\S]*?<\/miscellaneous-field>/,'<miscellaneous-field name="ar-editor-measure-layout-v1">[{"frames":[{"id":"bad"}]},{},{},{}]</miscellaneous-field>')),/cornice/);assert.throws(()=>importXml(xml.replace(/<miscellaneous-field[^>]*>[\s\S]*?<\/miscellaneous-field>/,'<miscellaneous-field name="ar-editor-measure-layout-v1">[]</miscellaneous-field>')),/coerente/)});

test('Note lunghe MusicXML: conserva durata e legature per tutti i suoni dell’accordo',()=>{const s=new ScoreSession(newScore({bars:1}));s.insert({start:0,midi:60,duration:'breve'});s.insert({start:0,midi:64,chord:true});const restored=importXml(scoreMusicXml(s.score)).score;assert.deepEqual(restored.events.map(e=>[e.start,e.duration,e.pitches,!!e.tieNext]),s.score.events.map(e=>[e.start,e.duration,e.pitches,!!e.tieNext]))});
test('Frammenti più brevi di 1/64 e terzine: durate MusicXML esatte al ritorno',()=>{for(const [meter,start,duration,dotted,tuplet] of [['1/64',0,'64th',true,false],['4/4',60,'quarter',false,true]]){const s=new ScoreSession(newScore({meter,bars:1}));s.insert({start,midi:60,duration,dotted,tuplet});const restored=importXml(scoreMusicXml(s.score)).score;assert.deepEqual(restored.events.map(e=>[e.start,e.duration,e.dotted,e.tuplet,!!e.tieNext]),s.score.events.map(e=>[e.start,e.duration,e.dotted,e.tuplet,!!e.tieNext]))}});
